Implement 'swap' command.
i3/i3 pull request #2496
Opened 2016-10-10 20:54 UTC by Airblader

This patch introduces a new command 'swap' that swaps two containers so
that they assume each other's position and geometry.

fixes #917

2016-10-10 20:54 UTC, Airblader commented
I'll still have to write quite a few testcases.

2016-10-10 21:00 UTC, Airblader commented
I also published a proof of concept implementation for #1758 using this feature here: https://github.com/Airblader/i3-sticky

2016-10-10 21:55 UTC, Airblader commented
And here in action, just because I think it's pretty cool: https://www.youtube.com/watch?v=kPGXqFPnswc

2016-10-11 05:57 UTC, Airblader commented on src/con.c
> +        con_focus(con_descend_focused(second));
So this behavior makes sense to me but we should discuss it. Let's assume one of the cons we swap is focused. If we swap within the same workspace, the con will maintain focus meaning focus will stay on the con but be in a different location. 

Now lets assume the focused container is swapped into another workspace. I think it'd be disruptive to focus another workspace plus tooling (which the swap feature likely requires in most use cases) can do that job. Otherwise scripts have to undo workspace switching which could cause a flicker. 

In essence the current behavior tries to make minimal changes to focus but does it in a meaningful way if we have to. Any deviating behavior should be handled by the tooling.

2016-10-11 05:57 UTC, Airblader commented on src/con.c
> +    if (con_is_floating(first) || con_is_floating(second)) {
From my sticky group example I've seen that I really want to make this work with floating windows but I think we should take this feature one step at a time. Both to keep the PR reasonably small and because traditionally these features are likely to come back with a bug or two.

2016-10-11 05:57 UTC, Airblader commented on src/con.c
> + * Swaps the two containers.
Should describe the behavior in more detail, in particular focus handling.

2016-10-11 05:57 UTC, Airblader commented on src/commands.c
> +    TAILQ_FOREACH(current, &owindows, owindows) {
Actually selecting more than one con makes no sense here. I think we should check for that, print a message and only handle the first matched container.

2016-10-11 05:57 UTC, Airblader commented on src/commands.c
> +    // TODO XXX Extract conversion to long
Todo

2016-10-11 18:46 UTC, Airblader commented on src/con.c
> +        con_focus(con_descend_focused(second));
This will actually change again slightly.

2016-10-11 19:08 UTC, Airblader commented
@stapelberg OK, I'll try to explain the focus behavior I'm going for now. I'd love if you could give it some thought because if you disagree, it'd be a substantial change so knowing early on is better (albeit I'm far past early already.)

There's basically three scenarios:

1. One of the two swapees is currently focused (or a parent thereof, I'll omit this from here on out) but they're on the same workspace.
2. One of the two swapees is currently focused, but the other one is on another workspace.
3. None of the swapees is focused.

And here's the intended focus behavior after swapping:

1. The previously focused container stays focused (which is in another physical location on the same workspace now.)
2. The non-focused swapee is focused in place of the other one. We cannot keep focus unless we switch workspaces, which is a drastic change. Keeping focus in the same physical location and the other involved swapee seems most intuitive to me.
3. The previously focused container stays focused and the swapees are inserted into the parents' focus stacks in the place where their counterpart used to be.

2016-10-12 19:26 UTC, Airblader commented on src/con.c
> +    FREE(con->deco_render_params);
This is actually a bug that I'm *pretty* sure affects existing usecases already, though I haven't really checked. We do call `force_split_blahblah` from `on_remove_child` which is called in the next line, but we do it _on the parent_. Also that function ignores leaf containers. This leads to a broken rendering of urgent containers after moving.

2016-10-12 19:26 UTC, Airblader commented
@stapelberg Well now I really hope you agree because I think this is ready for review now. I'll also do some more local testing, though.

2016-10-13 21:14 UTC, Airblader commented
I should add another test for swapping a fullscreen container.

2016-10-25 07:27 UTC, stapelberg commented on src/con.c
> +static bool _con_move_to_con(Con *con, Con *target, bool behind_focused, bool fix_coordinates, bool dont_warp, bool ignore_focus, bool fix_pecentage) {
I agree that this function needs refactoring in a followup PR. I don’t know yet which approach I like best, so I’ll leave that up to you and comment on it once I see actual code :).

2016-10-25 07:28 UTC, stapelberg commented on src/con.c
> +    FREE(con->deco_render_params);
Can you send a fix for that in a separate PR please?

2016-10-25 07:28 UTC, stapelberg commented
The focus behavior sounds good to me on first glance.

2016-10-25 07:46 UTC, stapelberg requested changes

2016-10-25 07:46 UTC, stapelberg commented on docs/userguide
> +normal command criteria process with the focused window being the usuall
s/usuall/usual/

2016-10-25 07:46 UTC, stapelberg commented on docs/userguide
> +using one of the following methids:
s/methids/methods/

2016-10-25 07:46 UTC, stapelberg commented on src/con.c
> +    if (fix_pecentage) {
s/fix_pecentage/fix_percentage/

2016-10-25 07:46 UTC, stapelberg commented on src/con.c
> +        ELOG("Only regular containers can be swapped, but found %d / %d\n", first->type, second->type);
Please improve this error message:

1. Please check each case individually, so that we can tell the user precisely which container is the problem.
2. Please include some container identification in the error message (`%p` and the title come to mind).
3. Please change the wording so that it’s clear what the magic numbers are (e.g. `[…] but found containers of type %d / type %d`).

2016-10-25 07:46 UTC, stapelberg commented on src/con.c
> +        DLOG("Cannot swap container with itself or into one another.\n");
Why DLOG instead of ELOG?

Also, like in my earlier comment, please split this into two conditionals. Should we use the same wording as in the documentation, i.e. “parent-child relationship”?

2016-10-25 07:46 UTC, stapelberg commented on src/con.c
> +        DLOG("Cannot swap because one target workspace is obscured.\n");
See my earlier comments about error messages.

2016-10-25 07:46 UTC, stapelberg commented on src/con.c
> +    while (first_prev_focus_head == first || first_prev_focus_head == second) {
Can `first_prev_focus_head == second` ever be true, given that we check `con_has_parent(first, second)` above?

2016-10-25 16:27 UTC, Airblader commented on src/con.c
> +        DLOG("Cannot swap container with itself or into one another.\n");
`first == second` isn't an error scenario, IMHO (it's a no-op). The other cases deserve an ELOG, agreed.

2016-10-25 16:27 UTC, Airblader commented
@stapelberg I'm *extremely* busy at work at the moment. I'll revisit this PR when I get time which might be a couple of weeks.

2017-05-12 07:00 UTC, Airblader commented on src/con.c
> +    while (first_prev_focus_head == first || first_prev_focus_head == second) {
Yes. If first and second are both inside the same tabbed container T[second, first].

2017-05-12 07:03 UTC, Airblader commented on docs/userguide
> +normal command criteria process with the focused window being the usuall
fixed

2017-05-12 07:03 UTC, Airblader commented on docs/userguide
> +using one of the following methids:
fixed

2017-05-12 07:03 UTC, Airblader commented on src/con.c
> +    if (fix_pecentage) {
fixed

2017-05-12 07:03 UTC, Airblader commented on src/con.c
> +        ELOG("Only regular containers can be swapped, but found %d / %d\n", first->type, second->type);
fixed

2017-05-12 07:03 UTC, Airblader commented on src/con.c
> +        DLOG("Cannot swap container with itself or into one another.\n");
fixed

2017-05-12 07:03 UTC, Airblader commented on src/con.c
> +        DLOG("Cannot swap because one target workspace is obscured.\n");
fixed

2017-05-12 07:08 UTC, Airblader commented on src/con.c
> +    FREE(con->deco_render_params);
done

2017-05-12 07:27 UTC, Airblader commented
@stapelberg I think this is good to go now, so perhaps you could review it again. Once merged I'll create issues for the followup improvements, but for now I'd like to get some experience with this feature before a next release.

2017-05-15 07:20 UTC, stapelberg approved these changes
Largely looks good — I’m happy to merge once the nits are addressed.

2017-05-15 07:20 UTC, stapelberg commented on src/con.c
> +        DLOG("Swapping container %p with itself, nothind to do.\n", first);
s/nothind/nothing

2017-05-15 07:20 UTC, stapelberg commented on src/con.c
> +    if (!con_fullscreen_permits_focusing(first_ws)) {
Is it strictly necessary to prevent swapping from working in this scenario? Similar to the sometimes-requested “fullscreen layout”, I can think of use-cases where one would want to swap some containers with the currently fullscreened container.

It’s also okay to address this in a subsequent PR if you’d like, just wanted to bring it up now.

2017-05-15 19:06 UTC, Airblader commented on src/con.c
> +    if (!con_fullscreen_permits_focusing(first_ws)) {
Yes, fullscreen is already on the list of followup PRs from last year. We should definitely allow it, but it seemed this PR is big enough as is. :-)

2017-05-15 19:06 UTC, Airblader commented
@stapelberg The nit is fixed.

2017-05-15 19:35 UTC, stapelberg approved these changes

2017-05-15 19:35 UTC, merged