i3-nagbar: add button flag to execute action with /bin/sh directly
i3/i3 pull request #2766
Opened 2017-05-07 13:46 UTC by MachFour

Implementation of ideas in #2765.

This change adds a new button type to i3-nagbar that allows execution of the user's command directly using /bin/sh rather than going though `i3-sensible-terminal`.

Documentation has been added to the manpage, and the output of `i3-nagbar --help`.

2017-05-09 13:41 UTC, Airblader commented
I haven't forgotten about this, but I'm a little low on time right now. Just letting you know that I will review it.

2017-05-12 06:16 UTC, Airblader requested changes
Just one small comment. :-)

2017-05-12 06:16 UTC, Airblader commented on i3-nagbar/main.c
> +    uint8_t exec_in_terminal;
Why is this not a bool?

2017-05-12 07:27 UTC, Airblader commented
Also please make sure to leave a comment when you fixed it so I am notified. Thanks!

2017-05-12 11:31 UTC, MachFour commented
You're right, of course it should be a bool. I had my C programming hat on!

Fixed now :)

2017-05-12 11:33 UTC, Airblader commented
Can you also squash those commits and include a reference to the ticket? Ideally a "fixes #…" so that Github can cross-reference PR and issue as well. Thanks! :-)

2017-05-12 11:54 UTC, MachFour commented
Yes, of course. I think I did the squash correctly but could you please double check?

2017-05-12 13:39 UTC, Airblader approved these changes
Great, thanks!

2017-05-12 13:39 UTC, merged