Updated [resize grow] to harvest from other windows
i3/i3 pull request #3194
Opened 2018-03-21 12:34 UTC by moodboom

Updated [resize grow] to be able to harvest pct from all other windows in the same container

2018-03-21 12:37 UTC, moodboom commented
I have a question about the best way to deal with [min_pct].  Can we make that a configuration instead of a hardcoded value?

2018-03-21 12:39 UTC, Airblader commented
I haven't yet looked at the PR, but what is min_pct for, anyway? From my original understanding of the proposal I don't see why we'd need something like that. It has always been about resizing other windows when one of the windows has reached its minimum size already.

I'd definitely prefer not having to add any configuration for this.

2018-03-21 12:44 UTC, moodboom commented
It looked to me like the original code bailed out if the request pushed the window into negative size.  So it would bail out randomly at some point where you WOULD have crossed into negative.  To get the resizing math right, I needed to know the actual precise preferred minimum size, which I assume would be something greater than zero.  The previous code always checked against zero.  Correct me if I'm wrong, that's my first take on it.

2018-03-21 12:47 UTC, moodboom commented
I'm not sure why Travis reported failure, the log looked okay to me, maybe I missed something?

2018-03-21 12:48 UTC, orestisf1993 commented
Run `clang-format -i src/commands.c`

2018-03-21 12:48 UTC, moodboom commented
Ah ok thank you @orestisf1993.

2018-03-21 13:09 UTC, Airblader commented
We explicitly got rid of some minimum width threshold not too long ago because there's just no way to please both small and large screen users, whether you use absolute or relative values (sorry, just remembered this right now). The idea there was that we don't have a good reason to have configuration for it since we can just use 0%.

With this change, I guess we would have a reason to re-introduce a minimum width. But of course we can't just reintroduce the problem in #3071. The problem with making this configurable is that some users will want it absolute, others percentage-based and soon enough people will want it to be a per-window setting etc.

I don't yet have an answer of what I'd prefer to do.

2018-03-21 13:13 UTC, moodboom commented
Absolutely understood.  That's why I was wondering about adding it, it will be different for different use cases I would think.  Everyone sets their parameters of [resize grow ...] differently.  We could set it as an additional parameter to [resize grow], but then it will get messy if it is ever needed elsewhere as well.

2018-03-21 13:17 UTC, moodboom commented
What about optional configurations, that can specify a pct_min or a px_min, and if neither are provided we default to zero?

One problem with using zero is that I've seen apps (gnome-terminal, nautilus) crash and misbehave if they get that small.

2018-03-21 20:22 UTC, moodboom commented
I tested further, and a min_pct of zero crashes i3.  A small value (eg 0.0001) works fine, but again, some windows misbehave and don't recover if they get that small.  Not i3's fault really, but seems best to defend against it.

After reading previous discussions, I understand the desire to keep things simple.  Any extra complexity has side effect.  To keep things as minimal as possible, I could add one config, min_pct, that would be optional, and default to something small (eg: .01).

2018-03-21 20:22 UTC, orestisfl requested changes
I generally like the new behaviour, thanks for the idea and the implementation.

I haven't reviewed this extensively.

2018-03-21 20:22 UTC, orestisf1993 commented on src/commands.c
> +    if (ppt > 0.0) {
`ppt` is an `int`, compare it to `0`.

2018-03-21 20:22 UTC, orestisf1993 commented on src/commands.c
> +    const double min_pct = 0.05;
Alternative to the `min_pct` configuration conversation: set it to `fabs(ppt / 100.0 / children)`. It should behave similarly to the current behaviour.

2018-03-21 22:28 UTC, moodboom reviewed
Thanks for the improvements!

2018-03-21 22:28 UTC, moodboom commented on src/commands.c
> +static int sort_cons_by_smallest_percent_cmp(const void *a, const void *b) {
Sure thing, I changed the name.  Wasn't sure about the second comment...?

2018-03-21 22:28 UTC, moodboom commented on src/commands.c
> +    if (first->percent < second->percent) {
Done

2018-03-21 22:28 UTC, moodboom commented on src/commands.c
> +    const double min_pct = 0.05;
Done

2018-03-21 22:28 UTC, moodboom commented on src/commands.c
> +    // Grow
Done

2018-03-21 22:28 UTC, moodboom commented on src/commands.c
> +    if (ppt > 0.0) {
Good one, done.  That means we can delay the decision about the configuration (although I vote yes fwiw :smile: ).

2018-03-21 22:44 UTC, moodboom commented
Note that with 

`    double min_pct = fabs(ppt / 100.0 / children);`

my windows get quite small and I see the misbehavior I've mentioned when windows get extremely small.

I'm still hoping we can add a min_pct configuration, but we can go with whatever you guys think best.

2018-03-21 22:47 UTC, orestisf1993 commented
Does this happen on `next` too?

2018-03-21 22:52 UTC, orestisf1993 commented on src/commands.c
> +static int sort_cons_by_smallest_percent_cmp(const void *a, const void *b) {
I'll leave a comment elsewhere.

2018-03-21 22:52 UTC, orestisf1993 commented on src/commands.c
> +        /* Sort cons by percent */
You can mention here that the sort is in descending order since a reader would have to figure it out by reading the compare function and consulting the `qsort` manpage if they don't remember the `*compar` function details.

2018-03-21 22:54 UTC, moodboom commented
To be honest, I have been juggling between i3 next and i3 gaps gaps-next, and mostly testing with gaps-next.  Shall I try in next, if you think that may be subtly different?

2018-03-21 22:59 UTC, moodboom commented on src/commands.c
> +        /* Sort cons by percent */
Ah ok will do!

2018-03-21 23:03 UTC, orestisf1993 commented
You can run i3 inside Xephyr, allowing you to change branches, make changes etc painlessly.
I have a script [here](https://github.com/orestisf1993/dotfiles/blob/b49a8f70c3578dff4f186bcf5d65adb9b97b6501/xorg/start-xephyr.sh) if you think it can help you.

I don't know the exact changes of i3-gaps but it would be nice to consider not breaking the i3-gaps users' workflow.

Anyway, do your windows get problematically small when you resize them on either `next` branch currently?

2018-03-21 23:05 UTC, moodboom commented
![image](https://user-images.githubusercontent.com/1799520/37742152-b5b46926-2d3a-11e8-82d7-08bd6fd74cfa.png)
Yes it will shrink even smaller than shown, and apps like gnome-terminal do not recover and redraw correctly afterwards.

2018-03-21 23:07 UTC, moodboom commented
I should mention that I bind grow and shrink directly to key movements, and click them quickly to resize, so I use a very small growth percent of 3%.

2018-03-21 23:25 UTC, orestisf1993 commented
Yeah, I am not sure about the current (`next`) behaviour either:

![2018-03-22-012043_1366x729_escrotum](https://user-images.githubusercontent.com/5778622/37742748-844af302-2d6f-11e8-973c-77a817e4f76f.png)

There are 3 terminals here, it gets buggy.

Actually, `double min_pct = fabs(ppt / 100.0 / children)` is not equivalent with the `next` behaviour after all. Containers can get 0 percent right now.

2018-03-21 23:51 UTC, moodboom commented
So I'm back to leaning towards a min_pct config.  What do you guys think?

2018-03-22 00:33 UTC, orestisf1993 commented
Eg from emacs crash:

```
X protocol error: BadDrawable (invalid Pixmap or Window parameter) on protocol request 70
When compiled with GTK, Emacs cannot recover from X disconnects.
This is a GTK bug: https://bugzilla.gnome.org/show_bug.cgi?id=85715
For details, see etc/PROBLEMS.
Fatal error 6: Aborted
```

2018-03-22 02:03 UTC, moodboom commented
Yep it appears I need to prevent really small sizes.  I would think there are cases now where i3 allows a nearly-minimum-size window to be shrunken and those problems would occur, right?

2018-03-22 03:29 UTC, moodboom commented
What if I used a minimum pct min_pct equal to the resize amount?  Does that seem reasonable in all cases?

2018-03-22 05:59 UTC, Airblader commented
Just as an explanation, when we got rid of the minimum size the argument was that all we need to prevent are zero sizes (which may rightfully break clients), but anything above zero is up to the user: generally, they wouldn't want to resize a window down to, say, one pixel anyway. And a client breaking permanently after being resized to a small but positive size is something where I'd consider the client to be broken; we cannot possibly accommodate that in the window manager.

I do like the suggestion of using the resize percentage as the minimum width (in some way or another) because I'd still like to avoid adding configuration for this. Can we go with that for now?

I haven't yet had time to look at the PR itself.

2018-03-22 10:02 UTC, moodboom commented
Sure that sounds good.  That's how it is coded at the moment, and is working well for me for now, let me know what you guys think.

2018-03-22 11:16 UTC, orestisf1993 commented on src/commands.c
> +    double min_pct = fabs(ppt / 100.0);
Now you can't resize for more than 50% right?

2018-03-22 11:38 UTC, orestisf1993 commented on src/commands.c
> +    double min_pct = fabs(ppt / 100.0);
And the tests fail. Because of it.

2018-03-22 12:17 UTC, moodboom commented on src/commands.c
> +    double min_pct = fabs(ppt / 100.0);
Ah ok, thanks.  I'll take a look at that use case when I can.

2018-03-22 15:11 UTC, moodboom commented
If you guys still want an automatic min_size, how about using the resize ppt, with validation that clips low and high values?  No less than .005, no more than .03.

Or I can add an official min_pct config, with a reasonable default of 5%.  In my opinion, it seems to be a logical thing to make configurable in a window manager that supports so many possible screen layouts.  Is there a use case that would be negatively impacted by such a configuration?

2018-03-22 15:45 UTC, moodboom commented
Sorry, coding on phone is not a good idea.  :-)  I'll work on this later.

2018-03-22 21:28 UTC, moodboom commented
Are the test failures due to the tests expecting old behavior?  It seems like that may be the case, but maybe you all are more familiar with the test suite and can help me with that.

Resizing seem to be working well enough here considering the constraints.  I think I've gotten min_pct as "automatic" as I can.  A really large ppt grow will only bring the target to take up an equal share of the screen, not optimal but not horrible I guess.  It still seems inferior to adding configuration.  I'll wait for further feedback.  Thanks all.

2018-03-22 21:37 UTC, orestisf1993 commented
No, the test should work. The failing test opens 4 windows and grows one of them to 50% with `resize grow width 10 px or 25 ppt`.

2018-03-22 22:05 UTC, moodboom commented
Correct me if I'm wrong, but I believe that the test will fail then with the new math.  min_pct will be set to fmax(.03,fmin(.25,fabs(.25))) = .25.  The "other" windows will not shrink as much as the test expects.  But it's doing what is expected with the new math.

As I mentioned, I'm not thrilled with the automatic behavior in all cases.

2018-03-22 22:09 UTC, orestisf1993 commented
I mean, the use case the test represents should still be a valid one. I don't agree with the new formula, kinda restrictive don't you think?

2018-03-22 22:16 UTC, moodboom commented
Yes I agree it is.  I'd like to add the config.  What are your thoughts on that?

2018-03-22 23:01 UTC, orestisf1993 commented
I'd like to give some time for Ingo or Michael to respond.

2018-03-22 23:04 UTC, moodboom commented
Sounds good, thanks @orestisf1993

2018-03-23 00:19 UTC, moodboom commented
@orestisf1993 maybe this auto min_pct is a little better, it's closer to your suggestion.

2018-03-23 18:28 UTC, Airblader commented
I'm still a bit undecided on it, to be honest. Out of curiosity, why is there the restriction to 0.03 in there? The other values can't ever reach zero, anyway, right?

Maybe a possible way forward would be getting some people to run this patch for a while to see how well it works out in everyday usage for different people; e.g., by asking on the mailing list and the subreddit. I'd like to rule out making things worse for some people here.

2018-03-23 19:36 UTC, moodboom commented
Thanks @Airblader will do.  I'll post a request to the subreddit and the mailing list.

The 0.03 is in there because if in general a window gets too small, things generally act up.  The previous approach of failing the grow if anything went negative was restrictive enough to prevent that in many cases.

I can remove it but it will more often result in very small sizes, if the grow ppt is small or there are a large number of small windows.  What would you prefer?

In my usage, I have found that a single user-modifiable min_pct config value is more precise than the auto behavior.

2018-03-23 19:41 UTC, Airblader commented
> I can remove it but it will more often result in very small sizes, if the grow ppt is small or there are a large number of small windows. What would you prefer?

I'd prefer removing it for now for the test and see how well it works without. The problem with a 0.03 is exactly the reason we removed the 5% limit we had previously: people have very differently sized monitors and there's just no single fixed number that fits everyone. And with the 0.03, we are practically re-introducing this limit since it'd be >= 0.03.

> In my usage, I have found that a single user-modifiable min_pct config value is more precise than the auto behavior.

Yes, and I really get understand that a configuration for this seems to make it easier. However, more configuration also means more complexity, which is why we try to avoid making things configurable that don't need to be configurable. If we find that there is no way around it, we can consider it; I'm not yet convinced that we can't find a good way to do it automatically. :-) Also, adding a configuration later on in a second step is easy, but removing one we didn't need to begin with is a breaking change.

2018-03-23 19:50 UTC, moodboom commented
@Airblader sounds great, thanks again!

2018-04-13 22:10 UTC, moodboom commented
Quick update: 

- The [request for feedback](https://redd.it/86nvzr) has 10 upvotes but no comments.
- I've been using it successfully here for three weeks with no issues, using a 6% minimum size.

2018-05-19 23:14 UTC, moodboom commented
Rebased onto latest i3 next commits.

2018-07-24 03:33 UTC, moodboom commented
UPDATE: This continues to perform well for me at 6% minimum size.  I have found that providing a specific min_pct configuration value is very helpful to make daily layout management more efficient, and prevent the current issues users are having with terminals crashing due to becoming (uselessly) small.

2018-08-24 19:38 UTC, orestisf1993 commented
What if we ensured that each container will have at least 1 pixel? Kinda like `px_resize_to_percent`.

2018-08-31 13:56 UTC, moodboom commented
@orestisf1993 we could ensure 1 pix, that would help prevent i3-related crashes without adding any new configuration.  

But it would not address the following, which I feel are important:
* the window manager will easily allow windows to become "unuseably small", which makes the UI unfriendly
* many applications crash when made "unuseably small"; this problem will likely persist for the near future

I could set up the 1-pixel-minimum limit to get this pull request approved, and tackle these other issues later, if you like.

2018-08-31 15:39 UTC, orestisf1993 commented
> I could set up the 1-pixel-minimum limit to get this pull request approved, and tackle these other issues later, if you like.

I think we could discuss this in a separate issue / PR and adjust the other resize functions as well.

Getting the final pixel size for split containers from `con->percent` isn't straightforward. I've added some code recently that dealt with this, see #3372.

For 1 pixel you'll need:
```
const orientation_t o = con_orientation(parent);
const int total = (o == HORIZ ? parent->rect.width : parent->rect.height);
const int target = (o == HORIZ ? 1 : 1 + con->deco_rect.height);
if (con->percent < (double)target / (double)total) {
    /* Less than 1px */
}
```

2022-07-18 16:12 UTC, closed without merging