Make "scratchpad show" return correct info
i3/i3 pull request #3230
Opened 2018-04-06 16:05 UTC by hwangcc23

Fix the issue #3227(https://github.com/i3/i3/issues/3227).

2018-04-06 16:08 UTC, Airblader commented
I'm sorry, I don't understand the fix. We want to return whether we have successfully shown a window or not. That means we need to use the information coming from `scratchpad_show`.

2018-04-06 16:39 UTC, hwangcc23 commented
Sorry. Misunderstood the problem.
Up.

2018-04-08 13:59 UTC, Airblader requested changes
Thanks for the update! There's a couple of changes and I also think we can & should add tests for all these different cases :-)

2018-04-08 13:59 UTC, Airblader commented on include/scratchpad.h
> + * Return true if a window is successfully showning.
There's a typo, but let's make change it to

> Returns true either if con was in the scratchpad and is now shown or if con was moved back into the scratchpad due to toggling.

2018-04-08 13:59 UTC, Airblader commented on src/commands.c
> +            result = scratchpad_show(current->con);
We should report a failure if there was a failure for any matched window (that's how we try to do it everywhere), so this should be `result &= …`.

2018-04-08 13:59 UTC, Airblader commented on src/scratchpad.c
> + * Return true if a window is successfully showning.
Same as above.

2018-04-08 13:59 UTC, Airblader commented on src/scratchpad.c
> +        return false;
This should return true. I think the true/false semantics should be that it's true whenever we successfully did something with `con`.

2018-04-08 13:59 UTC, Airblader commented on src/scratchpad.c
> +            return false;
Should be `true`.

2018-04-17 06:29 UTC, orestisf1993 commented
@hwangcc23
```perl
fresh_workspace;
open_window;
cmd 'move scratchpad';
my $result = cmd 'scratchpad show';
is($result->[0]->{success}, 1, 'call to scratchpad succeeded');

kill_all_windows;
$result = cmd 'scratchpad show';
is($result->[0]->{success}, 0, 'call to scratchpad failed');
```

2018-04-17 15:39 UTC, hwangcc23 commented on src/commands.c
> +            result |= scratchpad_show(current->con);
We should report a success if there is any matched window shown or hidden (due to toggled).
This is for passing the test with the criteria(The test case 2: Verify that 'scratchpad show' with the criteria returns correct info).

2018-04-17 15:40 UTC, hwangcc23 commented
Up

2018-04-17 21:48 UTC, orestisf1993 commented on testcases/t/298-scratchpad-show.t
> +# �~@� https://build.i3wm.org/docs/testsuite.html
Why not extend 185-scratchpad.t? Your `â~@¢` character seems to be wrong here too.

2018-04-17 21:54 UTC, orestisfl requested changes

2018-04-17 21:54 UTC, orestisf1993 commented on testcases/t/298-scratchpad-show.t
> +# �~@� https://build.i3wm.org/docs/testsuite.html
Why not extend 185-scratchpad.t? Your `â~@¢` character seems to be wrong here too.

2018-04-17 21:54 UTC, orestisf1993 commented on testcases/t/298-scratchpad-show.t
> +cmd 'workspace $ws';
What you do here: open a new workspace with a random name, then immediately switch to a workspace named `$ws` (you used single quotes). You don't need a variable or the `cmd` so I think you can remove both.

2018-04-17 21:54 UTC, orestisf1993 commented on testcases/t/298-scratchpad-show.t
> +cmd "workspace foo-1";
nitpick: just use `fresh_workspace`

2018-04-17 21:54 UTC, orestisf1993 commented on testcases/t/298-scratchpad-show.t
> +cmd "workspace foo-2";
same

2018-04-18 14:14 UTC, hwangcc23 commented
@orestisf1993 Thanks for the review.

Up.

2018-04-19 16:40 UTC, orestisfl approved these changes

2018-04-19 16:40 UTC, orestisf1993 commented on testcases/t/185-scratchpad.t
> +kill_all_windows;
nitpicky but can you add a newline after the comment blocks, like the rest of the file does?

2018-04-19 16:40 UTC, orestisf1993 commented on src/scratchpad.c
> + * Returns true either if con was in the scratchpad and is now shown or if con
This is slightly inaccurate because true is also returned  if there is an unfocused scratchpad on the current workspace. We don't really need to document the return value since it's a bit obvious.

2018-04-20 14:29 UTC, hwangcc23 commented on testcases/t/185-scratchpad.t
> +kill_all_windows;
OK. Will send the PR again.

2018-04-20 14:42 UTC, hwangcc23 commented
Requested changes are all done.

2018-04-20 14:51 UTC, orestisf1993 commented
Thanks. I'd merge it but I'll let @Airblader have a final look.

2018-04-21 15:57 UTC, Airblader approved these changes

2018-04-21 15:57 UTC, merged

2018-04-21 15:58 UTC, Airblader commented
Thanks!