[WIP] bspwm-like resize
i3/i3 pull request #3545
Opened 2018-12-05 10:42 UTC by xzfc

* resize both axis at the same time
* resize windows continuously during mouse drag, not afterwards

Video: http://dump.bitcheese.net/files/gaxygyl/1412.mp4

Fixes #1122.
Fixes #1412.

2018-12-05 10:42 UTC, xzfc commented
> resize windows continuously during mouse drag, not afterwards

This feature suffers greatly from #3544. I think we need to introduce some recursive function to calculate minimal size of the container.

2019-05-04 21:49 UTC, clapbr commented
Tested this PR as I could benefit for acessibility reasons, it works but has an issue. When I start dragging it resizes up to a point then deactivates quickly while I´m still moving, without me releasing either modkey or right click.

2019-05-06 03:54 UTC, xzfc commented
@clapbr I can't reproduce. Could you provide logs and/or steps to reproduce this?

2019-05-08 22:11 UTC, clapbr commented
> @clapbr I can't reproduce. Could you provide logs and/or steps to reproduce this?

Took some time to investigate, it was my trackballs fault. In middle of resize I was dragging my hand across the scroll and a scroll click interrupts the resizing.

2019-05-10 10:47 UTC, xzfc commented
@clapbr
> In middle of resize I was dragging my hand across the scroll and a scroll click interrupts the resizing.

This is the behavior of vanilla i3, this PR does nothing with it. Would you create a new issue in this repo please?

> edit: Is there a way to bind the resize action to a single key+cursor movement instead of right click+modifier+cursor movement?

No in the current version of i3. As an alternative, you can resize windows using keyboard only.

2019-10-23 05:44 UTC, danr commented
What is the status on this? Is it probable that this will be merged?

2019-10-23 10:32 UTC, xzfc commented
@danr
> What is the status on this?

It is still WIP, there are a few things I want to do.
I've pushed current revision just now, you may check if you're interested.

> Is it probable that this will be merged?

I hope so!

2020-02-24 10:53 UTC, xzfc commented
This PR is now ready for review.

Higlight:

* **Two-axis tiling resize**.  You can drag a 24-pixel window corner (purple) to perform a two-axis resize. Also, you can press Mod and drag a large corner inside the window (one-third of the window size).
![illustration](https://user-images.githubusercontent.com/5121426/75146543-40a7c580-56f3-11ea-9b26-e14718699323.png)

* **Live resize**: the tree is rendered during the resize process.

* You can still press **ESC to cancel** resizing and revert to the old state.

* Introduced the concept of the **minimum container size**.  E.g. the minimum width of leaf con with 10px borders is 21px (left border + right border + at least 1px for the window itself).  The minimum size is defined recursively, e.g. the minimum height of the vsplit is the sum of minimum sizes of its children.  The reason for this change: the live resize made it very easy to shrink containers as small as possible, so some restraints are required.

* Misc update: ignore the drag if i3 can't perform the resize.  Suppose the user tries to resize the rightmost window to the right using Mod+RMB drag.  Obliviously, i3 can't do this.  Before this PR, the drag has been propagated to the application (some apps would show a context menu).  After this PR, the drag would be ignored at all (and the cursor would be shown as ✕).  The reasoning behind this change: the user explicitly indicated their desire to resize the window by pressing the Mod key, and probably just miss clicked to the wrong part of the window.

* Bugfix in `tiling_resize()`: you can now resize the window with pixel border by dragging the top border.

2020-04-10 14:33 UTC, orestisfl commented
Can you please rebase?

2020-04-10 15:55 UTC, xzfc commented
@orestisfl Rebased.

2020-04-10 18:25 UTC, orestisfl requested changes
This is a bit much for one go. Let's start here.

2020-04-10 18:25 UTC, orestisfl commented on src/render.c
> +             * TODO: this isn't perfect as it fails to handle some corner cases,
Are these corner cases unique to this new implementation?

2020-04-10 18:29 UTC, orestisfl commented
> This PR is now ready for review.
> 
> Higlight:
> 
>     * **Two-axis tiling resize**.  You can drag a 24-pixel window corner (purple) to perform a two-axis resize. Also, you can press Mod and drag a large corner inside the window (one-third of the window size).
>       ![illustration](https://user-images.githubusercontent.com/5121426/75146543-40a7c580-56f3-11ea-9b26-e14718699323.png)
> 
>     * **Live resize**: the tree is rendered during the resize process.
> 
>     * You can still press **ESC to cancel** resizing and revert to the old state.
> 
>     * Introduced the concept of the **minimum container size**.  E.g. the minimum width of leaf con with 10px borders is 21px (left border + right border + at least 1px for the window itself).  The minimum size is defined recursively, e.g. the minimum height of the vsplit is the sum of minimum sizes of its children.  The reason for this change: the live resize made it very easy to shrink containers as small as possible, so some restraints are required.
> 
>     * ~Misc update: ignore the drag if i3 can't perform the resize.  Suppose the user tries to resize the rightmost window to the right using Mod+RMB drag.  Obliviously, i3 can't do this.  Before this PR, the drag has been propagated to the application (some apps would show a context menu).  After this PR, the drag would be ignored at all (and the cursor would be shown as ✕).  The reasoning behind this change: the user explicitly indicated their desire to resize the window by pressing the Mod key, and probably just miss clicked to the wrong part of the window.~ Done in [93e96f4](https://github.com/i3/i3/commit/93e96f4e6b28486c6b7be003e8db81bab30197ef).
> 
>     * Bugfix in `tiling_resize()`: you can now resize the window with pixel border by dragging the top border.

Paste this into the commit message as well. You don't need to reformat it, just delete the crossed-out part and paste it as markdown.

Didn't notice 93e96f4 was doing the same as this PR btw.

2020-04-10 21:30 UTC, xzfc commented on include/resize.h
> +border_t resize_get_borders_sides(Con *con, int x, int y, click_destination_t dest);
This could be reused in `handle_motion_notify()` in `src/handlers.c` to implement #3693.

2020-04-10 21:38 UTC, orestisfl commented on include/resize.h
> +border_t resize_get_borders_sides(Con *con, int x, int y, click_destination_t dest);
I think we can do that when we need it. Besides, I don't like the `resize_` prefix, it's misleading.

@Airblader wdyt?

2020-04-10 21:38 UTC, xzfc commented on include/resize.h
> +border_t resize_get_borders_mod(int x, int y, int width, int height);
Related question: should we update floating resize to match the new tiling resize? I.e. one-axis resize unless dragged by a corner.

If we decide to do so, then this function could be reused in `floating_resize_window()` in `src/floating.c`.

2020-04-10 21:52 UTC, xzfc commented on src/resize.c
> +        switch ((int)corner) {
I think enum is fine to store bitmasks, and i3 already has bitmask enums `Assignment::type` and `adjacent_t`. (however, `border_t` and `adjacent_t` look similar, probably should be merged into one)

2020-04-10 21:54 UTC, orestisfl commented on include/resize.h
> +border_t resize_get_borders_mod(int x, int y, int width, int height);
Ok, do you want to handle this in this PR?

2020-04-10 22:04 UTC, xzfc commented on include/resize.h
> +enum xcursor_cursor_t resize_cursor(border_t corner, bool both);
> how about `include_corners` (opposite effect)

It's not "both axis" but rather "use two-side arrow". I.e. if true (drag by border), horizontal resize would be `↔`. Otherwise (mod+drag), `⇤` or `⇥`.

2020-04-10 22:05 UTC, xzfc commented on include/resize.h
> +border_t resize_get_borders_mod(int x, int y, int width, int height);
Yes.

2020-04-10 23:17 UTC, orestisfl commented on src/resize.c
> +        switch ((int)corner) {
The cast is there to avoid a warning, this already tells us what the correct type of the variable should be. When we are using an enum as a type but allow values outside the defined range, we are lying.

About `Assignment::type`:
```
     * While the type is a bitmask, only one value can be set at a time. It is
     * a bitmask to allow filtering for multiple types, for example in the
     * assignment_for() function.
```
so in that case, the usage of enum is correct. The mentioned `assignment_for` is defined like this: `Assignment *assignment_for(i3Window *window, int type)`.

You are right about `adjacent_t`. I feel that it should be fixed, instead of being used as an argument to continue this practice.

2020-04-10 23:20 UTC, orestisfl commented on include/resize.h
> +enum xcursor_cursor_t resize_cursor(border_t corner, bool both);
So, what name are you proposing for the second argument?

2020-04-11 13:07 UTC, xzfc commented on src/resize.c
> +        switch ((int)corner) {
How about this? 
```c
typedef enum {
    RD_NONE = 0,

    RD_LEFT = (1 << 0),
    RD_RIGHT = (1 << 1),
    RD_UP = (1 << 2),
    RD_DOWN = (1 << 3),

    RD_UP_LEFT = RD_LEFT | RD_UP,
    RD_DOWN_LEFT = RD_LEFT | RD_DOWN,
    RD_UP_RIGHT = RD_RIGHT | RD_UP,
    RD_DOWN_RIGHT = RD_RIGHT | RD_DOWN,
} resize_direction_t;
```
It's still a bitmask, but values outside the defined ones aren't used.

2020-04-11 13:13 UTC, xzfc commented on include/resize.h
> +enum xcursor_cursor_t resize_cursor(border_t corner, bool both);
I'm thinking of this:
```c
/**
 * Return cursor which should be used during the resize process.
 *
 * `unidirectional` should be true when it is clear from the user perspective
 * which container is the main in the resizing process. In this case, a
 * single-headed arrow cursor is returned. Сontrariwise, e.g. in a case of drag
 * by the border between two windows, a two-headed arrow cursor is returned.
 *
 */
enum xcursor_cursor_t xcursor_type_for_resize_direction(resize_direction_t dir, bool unidirectional);
```

Probably, still there is a better name for the second argument.

2020-04-11 13:41 UTC, orestisfl commented on src/resize.c
> +        switch ((int)corner) {
SGTM

2020-04-11 13:53 UTC, orestisfl commented on include/resize.h
> +enum xcursor_cursor_t resize_cursor(border_t corner, bool both);
Yeah, I like the function name and the docstring. `unidirectional_arrow` might be better, to make it clear what "unidirectional" is referring to.

2020-04-11 14:03 UTC, orestisfl commented on include/resize.h
> +enum xcursor_cursor_t resize_cursor(border_t corner, bool both);
I'd like to document somewhere the high level intention of this: when dragging on the border between two containers the bidirectional arrow is used, otherwise it is the unidirectional.

No need to do it right now.

2020-04-11 14:14 UTC, orestisfl commented on src/click.c
> +static bool tiling_resize_for_border(Con *con, border_t border, xcb_button_press_event_t *event, bool use_threshold, bool both) {
This function does two things: finds participants and calls `resize_graphical_handler`. 3 of its arguments are only used in the `resize_graphical_handler` call. I feel we can refactor it so that the callers are responsible to call `resize_graphical_handler` (`floating_mod_on_tiled_client` already does in a specific case).

We can make the return type a `**Con` (`NULL` on failure) or a struct with `first_h`, `first_v` etc. `resize_graphical_handler` can also accept the same type as argument to avoid having 4 `Con*` arguments.

2020-04-11 14:40 UTC, xzfc commented on src/click.c
> +static bool tiling_resize_for_border(Con *con, border_t border, xcb_button_press_event_t *event, bool use_threshold, bool both) {
So, make an extended version of `resize_find_tiling_participants` for two axes?

```c
bool resize_find_tiling_participants(Con **current, Con **other, direction_t direction, bool both_sides); 
resize_direction_t resize_find_tiling_participants_two_axes(Con *con, resize_direction_t dir, Con *result[4]) {
    /* call resize_find_tiling_participants() multiple times */
    /* fill result[0] .. result[3] with first_h, first_v, second_h, second_v */
    /* return RD_NONE (== 0) on a failure */
}
```

2020-04-11 15:26 UTC, orestisfl commented on src/click.c
> +static bool tiling_resize_for_border(Con *con, border_t border, xcb_button_press_event_t *event, bool use_threshold, bool both) {
Yes, something like that

2020-04-12 03:20 UTC, xzfc commented on src/render.c
> +             * TODO: this isn't perfect as it fails to handle some corner cases,
Bad cases that I've found: stacked inside stacked inside vsplit, and stacked inside tabbed inside vsplit.
In this cases the calculated minimal height is one `deco_height` less that it should be (e.g. expected 80px, got 60px).

2020-04-12 03:21 UTC, xzfc commented
Added fixup commit.

2021-06-02 13:24 UTC, cmprmsd commented
This PR was quite ready wasn't it? :o

2021-08-25 07:00 UTC, cmprmsd commented
@orestisfl 
Congrats to your ingenuity badge on GitHub :D 

I wonder, if this PR conflict might get solved any time soon in order to merge it 😇

2022-04-20 21:11 UTC, cmprmsd commented
@xzfc Do you know if there where any blockers on this pull request? It seems a very good idea and your implementation looked already very progressed. 
@stapelberg I know this isn't exactly Chefsache but could you have a look at this PR? Thanks in advance :heart:

2022-04-22 06:30 UTC, stapelberg commented
Is @xzfc still interested in working on this? Otherwise someone else would need to take over this PR, rebase it, and address review comments.

2022-04-22 13:58 UTC, cmprmsd commented
I guess I need some tutoring on git rebasing etc :D 

Was this the correct procedure?

1. Fork @xzfc's repo
2. git clone my fork
3. git checkout 1412-bspwm-resize
4. git remote add upstream https://github.com/i3/i3/
5. git fetch upstream
6. git pull upstream next --rebase
7. atom . <- fix one conflict according to the git rebase issue
8. git rebase --continue
9. git log
11. git push -f origin 

Then I created the new PR draft. 
I don't know what's the proper way to take over an existing pull request but willing to try and help this PR getting forward.
It looks that too much stuff has been changed though..
See https://github.com/i3/i3/pull/4955 and https://github.com/i3/i3/pull/4955/files

2022-04-22 15:15 UTC, stapelberg commented
Yep, procedure seems correct to me.

@orestisfl Do you have time to review the new #4955 (given that you might still have some state on this feature), or would you prefer if someone else did?

2022-04-25 21:25 UTC, orestisfl commented
> Yep, procedure seems correct to me.
> 
> @orestisfl Do you have time to review the new #4955 (given that you might still have some state on this feature), or would you prefer if someone else did?

I left some comments. Changes includes part of the code I haven't touched a lot so other reviews would be great as well if we want to merge this faster.

It's safe to say this PR is stale at this point so I am closing it to consolidate discussion in the new one.

2022-04-25 21:25 UTC, closed without merging