Document floating properties in get_tree reply
i3/i3 pull request #3904
Opened 2020-01-12 20:55 UTC by sophacles

Update `doc/ipc` get_tree reply docs to include: `sticky` and `floating`.

2020-01-13 11:27 UTC, Airblader commented on docs/ipc
> +	be present on all workspaces
… on all workspaces on the same output. :-)

2020-04-20 18:20 UTC, orestisfl requested changes

2020-04-20 18:20 UTC, orestisfl commented on docs/ipc
> +	    "auto_off" - floating off
Whitespace seems off here

2020-04-20 18:20 UTC, orestisfl commented
What's the status here?

2022-03-06 17:10 UTC, sophacles commented
I was cleaning up some old todos and found that this was still open. Sorry on the long delay. It seems that since I opened this the `floating` field was documented elsewhere so I just removed my changes related to that. This now only has the `sticky` field documentation.

2022-03-06 17:10 UTC, sophacles commented on docs/ipc
> +	    "auto_off" - floating off
Someone else documented `floating` in the interim of me posting and me updating, so resolving this.

2022-03-07 06:54 UTC, Airblader approved these changes
Thanks!

2022-03-07 07:18 UTC, Airblader commented
@orestisfl It seems like I can't actually merge this since your review is still showing a requested change (weird, I would've thought I can override this…)

2022-09-21 17:26 UTC, orestisfl approved these changes

2022-09-21 17:27 UTC, orestisfl commented
Sorry, just noticed this.

2022-09-21 17:27 UTC, merged