Use OVER operator for drawing text
i3/i3 pull request #3947
Opened 2020-02-18 00:17 UTC by xzfc

Bring back commit 16160462a30f186f5b72bb551ba2188670d4e45c which is reverted by commit eba177342f00ee6efdc3eff05665f317e1a837ca.

Advantages of OVER over SOURCE:

* Subpixel font rendering (#3604).
* No transparent garbage around color emoji characters.

---

See https://github.com/i3/i3/pull/2925#issuecomment-556411728

**Renders**:
[before.png](https://user-images.githubusercontent.com/5121426/74693396-9fe17380-51e3-11ea-9037-2393d8a0b86a.png)
[after.png](https://user-images.githubusercontent.com/5121426/74693395-9d7f1980-51e3-11ea-8619-d79028cd6b23.png)

2020-02-18 05:49 UTC, stapelberg commented
Can you clarify which cairo version contains the fix, and ideally link to the fix? The only commit referenced in the issue that I can find is https://gitlab.freedesktop.org/cairo/cairo/commit/99427c3f4f6ce7ce3c95c4caa4d2b8ff7c0093d9, but that doesn’t mention OVER?

2020-02-18 06:10 UTC, Airblader reviewed
What happened to doing this conditionally on the alpha channel? This is no longer a pure i3-gaps problem.

2020-02-18 06:26 UTC, xzfc commented
@Airblader 
> What happened to doing this conditionally on the alpha channel? This is no longer a pure i3-gaps problem.

As I can see, current i3-next doesn't support RGBA fonts (aka hole-punching), and thus there is no `pango_font_alpha` variable.

2020-02-18 07:18 UTC, xzfc commented
@stapelberg
It seems the cairo commit `99427c3f` is the fix of the original issue with SOURCE described in #2908 (text isn't drawn if color emoji is present), which is different from the issues described in the current PR.

2020-02-18 07:22 UTC, stapelberg commented
> It seems the cairo commit `99427c3f` is the fix of the original issue with SOURCE described in #2908 (text isn't drawn if color emoji is present), which is different from the issues described in the current PR.

To ensure I understand correctly: the original motivation for this change is gone because of commit 99427c3f.

Can you outline why it’s now safe to re-introduce this change, given that it had to be reverted previously? This needs to go into the commit message.

2020-02-18 08:07 UTC, xzfc commented
> To ensure I understand correctly: the original motivation for this change is gone because of commit 99427c3f.

Yes.
| PR    | OP     | comment |
| ----- | ------ | - |
| old   | `SOURCE` | Text isn't drawn in cairo `1.15.8`..`1.15.10` if color emoji is present. |
| #2908 | `OVER`   | Original motivation: fix for cairo `1.15.8`. |
| #3604 | `SOURCE` | The previous patch has been reverted in i3 since it causes a problem in i3-gaps in case if the text alpha is 0 (https://github.com/i3/i3/pull/2925#issuecomment-328358822). |
| #3947 | `OVER`   | This PR. |

> Can you outline why it’s now safe to re-introduce this change, given that it had to be reverted previously? This needs to go into the commit message.

I think it has always been safe to use `OVER` in i3, and I've provided a fix for i3-gaps (https://github.com/i3/i3/pull/2925#issuecomment-556411728).

2020-02-18 08:14 UTC, Airblader commented
I won't stand in the way of this change due to the obvious benefit, but I still don't find it satisfactory that something in cairo simply doesn't seem to work correctly (perhaps I'm missing the bigger point as to why this cannot work correctly) and i3 needs to work around that.

With the idea of bringing i3-gaps into i3 this will also affect i3 (I was not aware the alpha channel on fonts wasn't in i3 yet – I thought it was), and the fix for i3-gaps isn't really a fix, but just reduces the issue a bit more (correct me if I'm wrong, but drawing emojis with alpha < 1.0 would still not work).

2020-04-21 08:06 UTC, orestisfl requested changes
> Can you outline why it’s now safe to re-introduce this change, given that it had to be reverted previously? This needs to go into the commit message.

@xzfc Can you add this into the commit message?

2022-11-05 16:01 UTC, stapelberg commented
Is this still a problem with modern versions of cairo?

I just tried to reproduce it, and when I use i3 with https://github.com/i3/i3/pull/5246 applied, this is the result.png that I get from the test script you provided in https://github.com/i3/i3/pull/2925#issuecomment-556411728 (Thanks! Very useful):

![result](https://user-images.githubusercontent.com/55506/200128843-de89b0ac-e632-4739-921c-4092f64e2f60.png)

Aside from my dpi leaking into the test, I don’t see any artifacts?

2023-07-21 17:05 UTC, closed without merging