i3-input: Make frame configurable with arguments
i3/i3 pull request #3963
Opened 2020-03-01 01:32 UTC by UncleAlbie

Add command line arguments to the i3-input tool setting
i3-input frame options. New arguments listed below.

    -C/--fg-color       foreground color (eg. #ffffff)
    -B/--bg-color       background color (eg. #ffffff)
    -W/--border-color   border color     (eg. #ffffff)
    -S/--padding        padding in (logical) pixels
    -b/--border         border width in (logical) pixels

2020-04-20 18:23 UTC, orestisfl commented
@Airblader are we interested in this?

2020-04-20 18:26 UTC, orestisfl commented
I feel that i3-input has better third-party alternatives and that we should put it in maintenance mode. Maybe even officially deprecate it. That said, this is not a horrible addition of complexity.

2020-04-20 18:44 UTC, Airblader commented
I agree that we don't intend i3-input to compete with the other tools and we see it as a bit of a reference implementation rather than a full fledged tool, but I've seen people use it quite happily over time. I think adding this is within reason in terms of complexity.

I don't think we'll actually deprecate i3-input anytime soon, though.

2020-10-13 08:36 UTC, orestisfl requested changes

2020-10-13 08:36 UTC, orestisfl commented on i3-input/main.c
> +        {"fg-color", required_argument, 0, 'C'},
i3lock uses lower-case 'c', maybe have some consistency since it's available? https://github.com/i3/i3lock/blob/f3b061233e28ad0cf920c9421adc2459b6920812/i3lock.c#L1025

```suggestion
        {"fg-color", required_argument, 0, 'c'},
```

2020-10-13 08:36 UTC, orestisfl commented on i3-input/main.c
> +        {"fg-color", required_argument, 0, 'C'},
Or even remove the short options since they don't generally make much sense.

2020-10-13 08:36 UTC, orestisfl commented on i3-input/main.c
> +    FREE(frameopts);
Does it need to be freed? It was never malloced in the first place

2023-07-21 17:06 UTC, closed without merging