WIP: Add situational exit codes
i3/i3 pull request #4107
Opened 2020-05-24 18:54 UTC by Arc676

Closes #3705.

I used `autoconfigure` to generate the `Makefile` and compile as specified in the instructions, but the generated binary seems to be a memory leak check wrapped around the actual executable so I can't test the exit codes. It seems there's a memory leak in one of the dependencies and whenever I run the executable, no matter what happens within `i3-input` I get the following output regarding the memory leaks and exit code 1.

How can I just run the newly compiled `i3-input` without the memory leak checker?

```
==417634==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3840 byte(s) in 6 object(s) allocated from:
    #0 0x7fe22a0dbfa0 in __interceptor_realloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:163
    #1 0x7fe229315661  (/usr/lib/libfontconfig.so.1+0x21661)

Indirect leak of 7040 byte(s) in 220 object(s) allocated from:
    #0 0x7fe22a0dbb3a in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7fe229301780  (/usr/lib/libfontconfig.so.1+0xd780)

Indirect leak of 3635 byte(s) in 287 object(s) allocated from:
    #0 0x7fe22a0628e6 in __interceptor_strdup /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cc:445
    #1 0x7fe229314e45 in FcValueSave (/usr/lib/libfontconfig.so.1+0x20e45)

Indirect leak of 3328 byte(s) in 104 object(s) allocated from:
    #0 0x7fe22a0dbd48 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7fe229315c09  (/usr/lib/libfontconfig.so.1+0x21c09)

Indirect leak of 2304 byte(s) in 72 object(s) allocated from:
    #0 0x7fe22a0dbd48 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7fe2293150d9  (/usr/lib/libfontconfig.so.1+0x210d9)

Indirect leak of 576 byte(s) in 18 object(s) allocated from:
    #0 0x7fe22a0dbd48 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7fe229314f77  (/usr/lib/libfontconfig.so.1+0x20f77)

Indirect leak of 144 byte(s) in 3 object(s) allocated from:
    #0 0x7fe22a0dbb3a in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7fe22930f03e in FcLangSetCreate (/usr/lib/libfontconfig.so.1+0x1b03e)

SUMMARY: AddressSanitizer: 20867 byte(s) leaked in 710 allocation(s).
```

2020-05-26 19:53 UTC, orestisfl commented
To avoid the leak checker you should use `--disable-sanitizers` during the `./configure` step

2020-05-26 20:02 UTC, orestisfl requested changes
Thank you for your PR

Can you also update the changelog https://github.com/i3/i3/blob/next/RELEASE-NOTES-next with `i3-input: add situational exit codes`

2020-05-26 20:02 UTC, orestisfl commented on i3-input/main.c
> +const int EXIT_INTERN_FAIL = 4;
Maybe we should avoid special purpose exit codes:
https://tldp.org/LDP/abs/html/exitcodes.html
https://stackoverflow.com/questions/1101957/are-there-any-standard-exit-status-codes-in-linux

2020-05-26 20:02 UTC, orestisfl commented on i3-input/main.c
> +        exit(EXIT_CANCEL);
This is a bit of a breaking change that could affect some existing user scripts that check for i3-input failure (everything other than zero is a failure in scripts, regardless of what special name we give to it)

2020-05-27 12:33 UTC, Arc676 commented on i3-input/main.c
> +const int EXIT_INTERN_FAIL = 4;
Good point. I'll shift the exit codes up to 3-6 to avoid the overlap with standard exit codes.

2020-05-27 12:38 UTC, Arc676 commented on i3-input/main.c
> +        exit(EXIT_CANCEL);
I understand. In the original feature request, an alternate exit code for "user canceled" was included; this is clearly incompatible with the existing expectation that simply canceling the operation doesn't count as a failure. How do you believe this conflict should be resolved? One possibility would be for "user canceled" to only yield a nonzero exit code if a command line argument is specified to request this, but I'd be curious to know what you think.

2020-05-27 14:05 UTC, orestisfl commented on i3-input/main.c
> +const int EXIT_INTERN_FAIL = 4;
On the other hand, many utilities like git seem to be using codes >= 1. Maybe we don't need to change anything and there doesn't seem to be a very established practice.

2020-05-27 14:11 UTC, orestisfl commented on i3-input/main.c
> +const int EXIT_INTERN_FAIL = 4;
But I do believe that we don't need so specific errors. I propose:
0 -> success
1 -> cancel (if we do it)
2 -> other errors

2020-05-27 14:20 UTC, orestisfl commented on i3-input/main.c
> +        exit(EXIT_CANCEL);
@Airblader WDYT?

2020-08-05 15:51 UTC, Arc676 commented on i3-input/main.c
> +        exit(EXIT_CANCEL);
Since the PR description specifies that it implements the original feature request, for now I've committed changes including the separate exit code for user canceled and rebased the PR branch with the new commits on the destination branch. As discussed previously, I've reduced the number of custom exit codes to just 2 cases.

The simplest way to both fulfill the feature request and prevent breaking changes seems to make this new behavior opt-in via command line argument. I'll implement this after getting confirmation that this would be in line with the design of `i3-input` so as to avoid adding irrelevant commits to this PR.

2020-10-20 07:16 UTC, orestisfl approved these changes

2020-10-20 07:19 UTC, orestisfl commented
Can you also squash the commits together? Rebasing with `next` is also a good idea because it will make travis pass more easily.

2020-10-20 07:20 UTC, orestisfl requested changes

2020-10-20 07:20 UTC, orestisfl commented on RELEASE-NOTES-next
> +  • i3-input: added different exit codes for when i3-input fails
And a very small nitpick

```suggestion
  • i3-input: add different exit codes for when i3-input fails
```

2020-10-20 07:38 UTC, orestisfl approved these changes

2020-10-20 07:38 UTC, merged

2020-10-20 07:38 UTC, orestisfl commented
Ok nvm, thank you!

2020-10-20 08:47 UTC, Arc676 commented
No problem. So I noticed in the end there wasn't a final decision (at least not in this thread) regarding the exit code for when the user cancels. Is this a change in behavior for `i3-input` for future releases?

2020-10-20 09:16 UTC, orestisfl commented
I implicitly accepted the exit code = 1 for canceling, hoping it will not be too much backwards incompatible and probably safer as well.