allow ppt values in move direction and move position commands
i3/i3 pull request #4189
Opened 2020-09-01 12:59 UTC by acheronfail

This adds support for `ppt` values to be used in the following `move` commands:

```
move <left|right|down|up> [<amount> [px|ppt]]
move position <pos_x> [px|ppt] <pos_y> [px|ppt]
```

Fixes #3519

2020-09-02 08:11 UTC, orestisfl requested changes

2020-09-02 08:11 UTC, orestisfl commented on docs/userguide
> +# The optional amount argument specifies how far the
Please briefly describe what `ppt` means for both cases, like in [Resizing containers/windows
](https://i3wm.org/docs/userguide.html#resizingconfig)

2020-09-02 08:11 UTC, orestisfl commented on src/commands.c
> +                    newrect.x -= is_ppt ? output->rect.width * ((double)amount / 100.0) : amount;
Here and below, why `output->rect.width`?

2020-09-02 21:01 UTC, acheronfail commented on src/commands.c
> +                    newrect.x -= is_ppt ? output->rect.width * ((double)amount / 100.0) : amount;
The intention here is that a command like:

```
move right 20 ppt
```

Will move the floating container to the right by 20% of the screen's width.
I used `con_get_output` and extracted the output's width in this fashion since I had seen it done in a similar way here: https://github.com/i3/i3/blob/04c489043c5caf2d4c07f16bf9606de581dc9800/src/commands.c#L674

2020-09-03 09:47 UTC, orestisfl commented on src/commands.c
> +                    newrect.x -= is_ppt ? output->rect.width * ((double)amount / 100.0) : amount;
Ok sorry, I misread the line before

2020-09-03 11:40 UTC, acheronfail commented
I only added some more text into the documentation but the build failed this time, I think it might have just been a flaky build? All the tests pass locally for me.

Any chance you could re-run it and see if that fixes it? (Unless I'm missing something else?)

2020-09-09 11:47 UTC, acheronfail commented
Just ran `git commit --amend --no-edit` to re-trigger the build.

2020-10-13 08:26 UTC, orestisfl approved these changes
Sounds good, thanks.

Just some minor nitpicks

2020-10-13 08:26 UTC, orestisfl commented on src/commands.c
> +            bool is_ppt = mode && strcmp(mode, "ppt") == 0;
nit: move this outside the loop and make it `const`

2020-10-13 08:26 UTC, orestisfl commented on src/commands.c
> +        DLOG("moving in direction %s, %ld %s\n", direction_str, amount, mode);
nit: move outside, it doesn't seem to change in the loop

2020-10-16 21:13 UTC, acheronfail commented
@orestisfl thanks for looking into that for me. :slightly_smiling_face: I should have addressed those minor nits now.

2020-10-20 07:26 UTC, orestisfl commented
Ok, final things:

1. Add a small line in https://github.com/i3/i3/blob/next/RELEASE-NOTES-next describing your change
2. Squash all commits into one
3. Rebase into next to make travis easier to pass

2020-10-20 08:01 UTC, acheronfail commented
Thanks for the help! I think that should be everything you asked for. :slightly_smiling_face:

2020-10-20 09:20 UTC, merged

2020-10-20 09:20 UTC, orestisfl commented
Thanks!