i3bar: add support for nonprimary output
i3/i3 pull request #4195
Opened 2020-09-13 22:50 UTC by mschuwalow

Adds support for a `nonprimary` output to i3bar. This is useful when configuring your bar using `primary`, as you can have one config for your main display and another for any additional display.

2020-10-06 11:08 UTC, wlhlm commented
Thanks for taking a stab at this. I've been interested in being able to configure i3bar on non-primary outputs for a while.

Associated issues: #4083, https://github.com/i3/i3/issues/2311#issuecomment-213966121

Though, looking at your code, it looks quite limited to me: IIUIC, this will pick the first non-primary output and stop. This makes sense if you have two or less outputs, otherwise it will just pick the first non-primary output from the list and that depends on how the list is assembled (not sure if deterministic). I think it makes more sense if the `nonprimary` option displays the bar on all non-primary outputs not just the first one. If you have more then two outputs and want to display the bar only  on a single non-primary output, I thinks it's better to hardcode the output.

2020-10-08 21:50 UTC, mschuwalow commented
As far as I can tell this works with any number of outputs. I'm currently using this with 3 monitors and everything works as expected https://github.com/mschuwalow/nixos-config/blob/master/profiles/desktop/i3.nix#L455.

My understanding of that part of the code is that one map will be sent for each output, so it's enough for us to check whether we are supposed to handle it. In the case of `nonprimary` that means short-circuiting as soon as we see an output that is not marked as primary.

2020-10-09 17:50 UTC, wlhlm commented
> As far as I can tell this works with any number of outputs. I'm currently using this with 3 monitors and everything works as expected

OK, I misread the code then. Good to hear! 👍

2020-10-16 13:59 UTC, orestisfl requested changes
Thanks! Minor changes.

Also, question: Have you verified that the bar location is updated when you change the primary output? It should in theory work.

2020-10-16 13:59 UTC, orestisfl commented on docs/userguide
> +output primary|nonprimary|<output>
Please briefly explain what nonprimary means. I.e., every output except the primary

2020-10-16 13:59 UTC, orestisfl commented on i3bar/src/outputs.c
> +                (strcasecmp(config.outputs[c], "nonprimary") == 0 && !params->outputs_walk->primary)) {
I think this will be  a bit more readable with a const:
```c
const bool is_primary = params->outputs_walk->primary
```

```suggestion
                (strcasecmp(config.outputs[c], "primary") == 0 && is_primary ||
                (strcasecmp(config.outputs[c], "nonprimary") == 0 && !is_primary)) {
```

2020-10-18 12:42 UTC, mschuwalow commented
> Thanks! Minor changes.
> 
> Also, question: Have you verified that the bar location is updated when you change the primary output? It should in theory work.

Yes, I can confirm that it works. :+1:

2020-10-19 07:20 UTC, orestisfl approved these changes
Great!

Last chore:
1. Add a line in https://github.com/i3/i3/blob/next/RELEASE-NOTES-next that describes the change
2. Squash all commits into one

2020-10-22 17:38 UTC, mschuwalow commented
> Great!
> 
> Last chore:
> 
> 1. Add a line in https://github.com/i3/i3/blob/next/RELEASE-NOTES-next that describes the change
> 2. Squash all commits into one

Done. Thanks for guiding me through the process :smile:

2020-10-22 20:44 UTC, orestisfl reviewed
Thanks!

2020-10-22 20:44 UTC, orestisfl commented on RELEASE-NOTES-next
> +  • i3bar: add “nonprimary” output option
Changed the release notes a bit, this is more consistent with how we write them.

2020-10-24 12:29 UTC, merged