Add coordinates relative to the crurrent output in i3bar click events
i3/i3 pull request #4214
Opened 2020-10-06 19:48 UTC by burik666

Currently i3bar click events provide x and y coordinates relative to all monitors.
I've added coordinates relative to the current output.

```
+-----------+-----------+
|           |   i3bar   |
|           +-----------+
|   HDMI-0  |    DP-0   |
| 1920x1080 | 2560x1080 |
+-----------+-----------+
```
When you click in the top right corner of the DP-0, i3bar will provide something like this:
```json
{
  "x": 4480,
  "y": 10,
  "output_x": 2560,
  "output_y": 10,
}
```
This is useful for creating a `rofi` menu or something else.
`rofi -show run -location 1 -xoffset ${I3_OUTPUT_X} -yoffset ${I3_OUTPUT_Y}`

2020-10-13 08:13 UTC, orestisfl commented
So, isn't this something that can be calculated by the script that calls rofi? Plus, can't rofi be called with a global position?

2020-10-13 10:28 UTC, burik666 commented
These coordinates are difficult to calculate by a script.
<details><summary>output_xy.sh</summary>

```bash
#!/usr/bin/env bash
# from https://superuser.com/a/1238384

OFFSET_RE="\+([-0-9]+)\+([-0-9]+)"

# Get the window position
eval "$(xdotool getmouselocation --shell)"

# Loop through each screen and compare the offset with the window
# coordinates.
monitor_index=0
while read name width height xoff yoff
do
    if [ "${X}" -ge "$xoff" \
      -a "${Y}" -ge "$yoff" \
      -a "${X}" -lt "$(($xoff+$width))" \
      -a "${Y}" -lt "$(($yoff+$height))" ]
    then
        monitor=$name
        OUTPUT_X=$((X - xoff))
        OUTPUT_Y=$((Y - yoff))
        break
    fi
    ((monitor_index++))
done < <(xrandr | grep -w connected |
    sed -r "s/^([^ ]*).*\b([-0-9]+)x([-0-9]+)$OFFSET_RE.*$/\1 \2 \3 \4 \5/" |
    sort -nk4,5)

# If we found a monitor, echo it out, otherwise print an error.
if [ ! -z "$monitor" ]
then
    echo $OUTPUT_X $OUTPUT_Y
    exit 0
else
    echo "Couldn't find any monitor for the current window." >&2
    exit 1
fi
```

</details>


rofi only supports positioning relative to the current screen. https://github.com/davatorium/rofi/wiki/WindowPosition

2020-10-20 17:01 UTC, orestisfl commented
@Airblader if you agree that this is something that is hard to work around & worthy to implement, I will merge it.

I would however prefer `relative_{x,y}` than `output_{x,y}`

2020-10-20 17:05 UTC, burik666 commented
@orestisfl,
`relative_{x,y}` already used.

https://i3wm.org/docs/i3bar-protocol.html#_click_events
```
relative_x, relative_y
    Coordinates where the click occurred, with respect to the top left corner of the block
```

2020-10-23 09:00 UTC, burik666 commented
@Airblader, what do you think about this?

2020-10-23 09:16 UTC, orestisfl requested changes
I'd say we can go ahead

I found a typo.

Have you tested the exact correctness of the coordinates? I'd like to run it a bit myself as well, just making sure that you get exactly the correct number.

2020-10-23 09:16 UTC, orestisfl commented on RELEASE-NOTES-next
> +  • i3bar: add coordinates relative to the crurrent output in i3bar click events
```suggestion
  • i3bar: add coordinates relative to the current output in i3bar click events
```

2020-10-23 09:18 UTC, orestisfl commented
Other things: Do not introduce merge commits in PRs, use `rebase` instead. One simple way to fix this right now is `git reset --hard origin/next && git cherry-pick 3a9ac8c6fa50ebf6fde67209d6fd9d7bebd6adfb`.

Include the extra information in the PR description inside the git commit message.

2020-10-23 09:20 UTC, orestisfl commented
Oh and the typo is in the commit message as well :smiley:

2020-10-23 09:37 UTC, burik666 commented
@orestisfl,

Yes, I tested with different xrandr configurations.
This works great.

2020-10-23 09:42 UTC, Airblader commented
> @Airblader, what do you think about this?

I haven't had a chance to look at the PR from the code-level, but completely trust @orestisfl in that regard. As for the feature, I think it makes sense, the naming is fine (given that relative_ is already used), so let's get it shipped.

That said, @orestisfl , I think we may want to be a bit selective with which features we merge into stable now so we don't merge things right before the next release without having some testing period. I think this one is probably fine as (apart from potential crashes) it shouldn't affect any existing things, but you can make that call.

2020-10-23 09:46 UTC, orestisfl approved these changes
Great!

Last thing is to just copy-paste the PR description code in the commit message. The reason is to not have commit context (e.g. when using `git blame`) depend on GitHub.

2020-10-23 10:41 UTC, burik666 commented
@orestisfl, thanks a lot for your help with this PR.

2020-10-23 11:56 UTC, merged

2020-10-23 11:57 UTC, orestisfl commented
Thank you!