Implement context-sensitive tab-clicking behavior
i3/i3 pull request #4230
Opened 2020-10-26 02:23 UTC by Xyene

This commit makes it so that when clicking on a tab for the first time,
its inactive-focused child is focused. This matches i3 behavior when
scrolling on tabs.

A second click on the tab titlebar focuses the tab container itself.

Subsequent clicks cycle between these two states.

Closes #4225.

2020-10-26 06:28 UTC, orestisfl requested changes

2020-10-26 06:28 UTC, orestisfl commented on src/click.c
> +            con_to_focus = con_descend_focused(con_descend_direction(con, D_LEFT));
Unfortunately, that's not correct but it shouldn't be too hard. You will need to write a custom `con_descend_focused` that does not stop at `focused`.

For a case where your approach fails:
`T[ H[ a* b ] ]` after two clicks becomes ``T[ H[ a b* ] ]`

2020-10-27 01:02 UTC, Xyene commented on src/click.c
> +            con_to_focus = con_descend_focused(con_descend_direction(con, D_LEFT));
Ah, I figured something was wonky about that -- I've switched to a custom version now.

2020-11-11 05:29 UTC, Xyene commented
@orestisfl gentle ping -- is this something that would be wanted upstream, and if so, is there anything else I should do on my end?

2020-11-11 08:53 UTC, orestisfl commented
Sorry for the wait.

I am in favor of the change.

Can you also update this file please: https://github.com/i3/i3/blob/next/RELEASE-NOTES-next

2020-11-11 08:58 UTC, Airblader commented
@orestisfl Same here, I'd rather wait with this until after the release. The change is small, but focus handling has been a cause of many bugs in the past, so giving this a bit of time on next before going into main would be good.

2020-11-13 04:21 UTC, Xyene commented
Sounds good! I assume I should wait until after 4.19 is released to update https://github.com/i3/i3/blob/next/RELEASE-NOTES-next?

2020-11-15 22:10 UTC, Xyene commented
Now that 4.19 has been released, I've gone ahead and updated https://github.com/i3/i3/blob/next/RELEASE-NOTES-next.

2021-01-01 15:07 UTC, orestisfl approved these changes
Can you please rebase so that we can merge this?

Also potential suggestion

2021-01-01 15:07 UTC, orestisfl commented on RELEASE-NOTES-next
> +  • allow focusing split tab containers by double-clicking their titlebars
Does this sound better?

```suggestion
  • alternate focusing tab/stack children-parent containers by clicking on their titlebars
```

2021-01-01 21:06 UTC, Xyene commented on RELEASE-NOTES-next
> +  • allow focusing split tab containers by double-clicking their titlebars
Yes, this sounds better to me too -- thanks.

2021-01-01 21:09 UTC, Xyene commented
I've rebased and updated RELEASE-NOTES-next.

2021-01-01 21:10 UTC, orestisfl approved these changes
Thank you!

2021-01-01 21:17 UTC, merged