i3-nagbar: add possibility to open bar on focused monitor
i3/i3 pull request #4244
Opened 2020-11-03 14:46 UTC by ekarpp

Closes #3692

i3-nagbar will open by default on the monitor with input focus and using the flag -p on the primary monitor.

2020-11-04 08:33 UTC, orestisfl requested changes

2020-11-04 08:33 UTC, orestisfl commented on i3-nagbar/main.c
> +    if (position_on_focused) {
I feel that this will be more readable if we split this in two different functions

2020-11-05 09:34 UTC, orestisfl requested changes

2020-11-05 09:34 UTC, orestisfl commented on i3-nagbar/main.c
> +    goto free_resources;
```suggestion
```

2020-11-05 09:34 UTC, orestisfl commented on i3-nagbar/main.c
> +    free(geometry);
I wonder if it is preferential to fall-back to primary if we fail here. WDYT?

2020-11-05 18:00 UTC, ekarpp commented on i3-nagbar/main.c
> +    free(geometry);
I think this is a nice idea. I suppose when the primary output is preferred, the output with input focus could also be used as a fallback?

2020-11-05 19:53 UTC, orestisfl commented on i3-nagbar/main.c
> +    free(geometry);
Not really important but maybe no since `-p` is an opt-in option

2020-11-06 10:15 UTC, orestisfl requested changes

2020-11-06 10:15 UTC, orestisfl commented on i3-nagbar/main.c
> +
```suggestion
```

2020-11-06 10:15 UTC, orestisfl commented on i3-nagbar/main.c
> +
Travis failed because of this

2020-11-06 10:15 UTC, orestisfl commented on i3-nagbar/main.c
> +    bool error = false;
```suggestion
    bool success = false;
```
Instead of having multiple `error` assignments, just have a `success` one and ...

2020-11-06 10:15 UTC, orestisfl commented on i3-nagbar/main.c
> +    result->y = coordinates->dst_y;
```suggestion
    result->y = coordinates->dst_y;
    success = true;
```

2020-11-06 10:15 UTC, orestisfl commented on i3-nagbar/main.c
> +        error = true;
```suggestion
```

2020-11-06 10:15 UTC, orestisfl commented on i3-nagbar/main.c
> +        error = true;
```suggestion
```

2020-11-06 10:15 UTC, orestisfl commented on i3-nagbar/main.c
> +        error = true;
```suggestion
```

2020-11-06 11:46 UTC, ekarpp commented
I guess this Travis failure is unrelated to the changes?

2020-11-06 12:01 UTC, orestisfl commented
It's a formatting error, check my comments

2020-11-06 13:57 UTC, ekarpp commented
Sorry, I should have clarified, I meant the newer Travis failure. I already pushed a change based on your comments. The new failure was caused by (I think?) a parse error in one of the tests.

2020-11-08 09:24 UTC, orestisfl approved these changes
LGTM. @Airblader any input? Is there any shorter sequence of X calls that can get us the information needed here?

2020-11-08 09:31 UTC, Airblader commented
> Is there any shorter sequence of X calls that can get us the information needed here?

I don't think so, this seems fine, and frankly is less work than the primary output which requires RandR. 

I actually think we should make this the default, not a flag, though. I also think we could just remove the primary placement, though I'd keep it behind the flag for now just in case someone prefers it. We could open an issue for removing it in the release after, and maybe when using the flag print a warning to stderr to ask users to provide feedback if they want to keep using that?

2020-11-08 09:40 UTC, Airblader commented
I need to read more carefully, this is already the new default, so ignore that part. As for deprecating that primary flag we can also handle this outside of the PR. Sorry :-)

2020-11-24 09:03 UTC, orestisfl commented
@ekarpp can you rebase with next and also copy the extra information in the commit message:

```
Closes #3692

i3-nagbar will open by default on the monitor with input focus and using the flag -p on the primary monitor.
```

2020-11-24 18:50 UTC, ekarpp commented
Rebased, thanks for helping me with this PR.

2020-11-29 22:34 UTC, merged

2020-11-29 22:34 UTC, orestisfl commented
Thanks!