i3-dump-log -f: switch from pthreads to UNIX sockets
i3/i3 pull request #4321
Opened 2021-01-15 15:18 UTC by stapelberg

2021-01-15 15:27 UTC, Airblader approved these changes
This isn't really my area of expertise, so all I can say is "looks OK to me" :-)

2021-01-15 15:50 UTC, orestisfl commented
I'll try to review this during the weekend

On Fri, Jan 15, 2021, 16:27 Ingo Bürk <notifications@github.com> wrote:

> *@Airblader* approved this pull request.
>
> This isn't really my area of expertise, so all I can say is "looks OK to
> me" :-)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/i3/i3/pull/4321#pullrequestreview-569358148>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABMCZPVQCSPDMQW7Q7TRNS3S2BNF3ANCNFSM4WEGKUNQ>
> .
>

2021-01-15 20:23 UTC, orestisfl requested changes
Some nitpicks for now.

2021-01-15 20:23 UTC, orestisfl commented on src/ipc.c
>  int ipc_create_socket(const char *filename) {
Maybe having this function is now redundant?

2021-01-15 20:23 UTC, orestisfl commented on i3-dump-log/main.c
> +    (void)fcntl(sockfd, F_SETFD, FD_CLOEXEC);
nitpick for consistency:
```suggestion
    fcntl(sockfd, F_SETFD, FD_CLOEXEC);
```

2021-01-15 20:23 UTC, orestisfl commented on i3-dump-log/main.c
> +    if (connect(sockfd, (const struct sockaddr *)&addr, sizeof(struct sockaddr_un)) < 0)
Nit: Add curly braces

2021-01-15 20:23 UTC, orestisfl commented on i3-dump-log/main.c
> +    // Same size as the buffer used in log.c vlog():
```suggestion
    /* Same size as the buffer used in log.c vlog(): */
```

2021-01-15 20:23 UTC, orestisfl commented on i3-dump-log/main.c
> +            // TODO: reconnect when i3 restarts, handle transient failures
Open TODO? I would prefer an issue rather than a comment.

2021-01-15 20:23 UTC, orestisfl commented on src/log.c
> +        // TODO: In case slow connections turn out to be a problem here
Maybe an `XXX` instead of a `TODO` here? Also C-style comments.

2021-01-15 20:23 UTC, orestisfl commented on i3-dump-log/main.c
> +            exit(0);  // i3 closed the socket
```suggestion
            exit(0);  /* i3 closed the socket */
```

2021-01-15 20:23 UTC, orestisfl commented on libi3/create_socket.c
> +    (void)fcntl(sockfd, F_SETFD, FD_CLOEXEC);
```suggestion
    fcntl(sockfd, F_SETFD, FD_CLOEXEC);
```

2021-01-15 20:23 UTC, orestisfl commented on libi3/create_socket.c
> +        mkdirp(dir, DEFAULT_DIR_MODE);
```suggestion
    if (!path_exists(dir)) {
        mkdirp(dir, DEFAULT_DIR_MODE);
    }
```

2021-01-15 20:23 UTC, orestisfl commented on libi3/create_socket.c
> +    if ((sockfd = socket(AF_LOCAL, SOCK_STREAM, 0)) < 0) {
```suggestion
    int sockfd = socket(AF_LOCAL, SOCK_STREAM, 0);
    if (sockfd < 0) {
```

2021-01-15 20:23 UTC, orestisfl commented on libi3/nonblock.c
> +        err(-1, "Could not set O_NONBLOCK");
```suggestion
    if (fcntl(sockfd, F_SETFL, flags) < 0) {
        err(-1, "Could not set O_NONBLOCK");
    }
```

2021-01-15 20:23 UTC, orestisfl commented on src/log.c
> +    (void)fcntl(fd, F_SETFD, FD_CLOEXEC);
```suggestion
    fcntl(fd, F_SETFD, FD_CLOEXEC);
```

2021-01-17 16:10 UTC, stapelberg commented on src/log.c
> +    (void)fcntl(fd, F_SETFD, FD_CLOEXEC);
Why the suggestion? fcntl returns an error, so to signal to static analysis tools, we should add `(void)` to signal we know we’re not handling an error here. Is that no longer necessary?

2021-01-17 16:29 UTC, stapelberg commented on i3-dump-log/main.c
> +            // TODO: reconnect when i3 restarts, handle transient failures
Issue #4325 filed.

2021-01-17 16:31 UTC, stapelberg commented
PTAL

2021-01-19 09:50 UTC, orestisfl commented on src/log.c
> +    (void)fcntl(fd, F_SETFD, FD_CLOEXEC);
I don't think that the compiler complains about unused return values and the rest of the codebase does not use this idiom. However, I am fine with changing our approach with this hereafter.

2021-01-19 12:29 UTC, orestisfl commented on src/log.c
> +    (void)fcntl(fd, F_SETFD, FD_CLOEXEC);
And, technically, to be consistent with this practice we would technically have to apply it to common functions that are usually not checked like `printf` which can return `< 0` on failure.

2021-01-19 16:23 UTC, stapelberg commented on src/log.c
> +    (void)fcntl(fd, F_SETFD, FD_CLOEXEC);
> I don't think that the compiler complains

No, I think it was `clang-analyze`, but we removed that from our CI in 1a2ce3edaf4cb81acf1cda504151c8d96ff27a60 (2017), so I doubt anyone runs it…

> And, technically, to be consistent with this practice we would technically have to apply it to common functions that are usually not checked like `printf` which can return `< 0` on failure.

I don’t think it makes sense to check (or annotate) e.g. `printf`. What are you going to do when printing fails? Printing an error will likely fail, too ;)

I think the annotation should be placed where reviewers would otherwise ask to handle the error, to convey that we thought about an error check and decided against it.

2021-01-19 18:37 UTC, orestisfl requested changes
Canceling `i3-dump-log -f` with ctrl-c crashes i3 for me. If you can't reproduce this tell me so that I can provide more details.

2021-01-19 18:37 UTC, orestisfl commented on src/main.c
> +        config.log_stream_socket_path = get_process_filename("log-stream-socket");
This variable does not seem to need to reside in `config.`

Applying this diff compiles:

```diff
diff --git a/include/configuration.h b/include/configuration.h
index eaf71829..11cdde0d 100644
--- a/include/configuration.h
+++ b/include/configuration.h
@@ -93,7 +93,6 @@ struct Config {
     i3Font font;
 
     char *ipc_socket_path;
-    char *log_stream_socket_path;
     char *restart_state_path;
 
     layout_t default_layout;
diff --git a/src/main.c b/src/main.c
index 49c23521..54b38f44 100644
--- a/src/main.c
+++ b/src/main.c
@@ -637,11 +637,6 @@ int main(int argc, char *argv[]) {
             config.ipc_socket_path = sstrdup(config.ipc_socket_path);
     }
 
-    if (config.log_stream_socket_path == NULL) {
-        /* Chose a file name in /tmp/ based on the PID */
-        config.log_stream_socket_path = get_process_filename("log-stream-socket");
-    }
-
     if (config.force_xinerama) {
         force_xinerama = true;
     }
@@ -862,7 +857,10 @@ int main(int argc, char *argv[]) {
         ev_io_start(main_loop, ipc_io);
     }
 
-    int log_socket = create_socket(config.log_stream_socket_path, &current_log_stream_socket_path);
+    /* Chose a file name in /tmp/ based on the PID */
+    char *log_stream_socket_path = get_process_filename("log-stream-socket");
+    int log_socket = create_socket(log_stream_socket_path, &current_log_stream_socket_path);
+    free(log_stream_socket_path);
     if (log_socket == -1) {
         ELOG("Could not create the log socket, i3-dump-log -f will not work\n");
     } else {
```

2021-01-19 21:33 UTC, orestisfl commented
To avoid exiting with an error, here is a simple patch:

```diff
diff --git a/src/log.c b/src/log.c
index 8ef9914dc..4b63ba914 100644
--- a/src/log.c
+++ b/src/log.c
@@ -411,6 +411,6 @@ void log_broadcast_to_clients(const char *message, size_t len) {
         /* XXX: In case slow connections turn out to be a problem here */
         /* (unlikely as long as i3-dump-log is the only consumer), introduce */
         /* buffering, similar to the IPC interface. */
-        swrite(current->fd, message, len);
+        (void)writeall(current->fd, message, len);
     }
 }
```

It doesn't make sense to crash i3 because some `i3-dump-log` client is misbehaving anyway.

2021-01-20 08:31 UTC, stapelberg commented on src/main.c
> +        config.log_stream_socket_path = get_process_filename("log-stream-socket");
Done.

2021-01-20 08:32 UTC, stapelberg commented
> To avoid exiting with an error, here is a ~simple~ patch:

Thanks, merged!

2021-01-20 09:56 UTC, orestisfl approved these changes
SGTM!

2021-01-20 10:09 UTC, orestisfl commented
Oh one last thing: update the release notes

2021-01-20 17:22 UTC, stapelberg commented
> Oh one last thing: update the release notes

Done!

2021-01-20 17:31 UTC, orestisfl commented
Ok, feel free to squash merge :)

2021-01-20 20:40 UTC, merged