Removed "," from rofi command which threw an error
i3/i3 pull request #4331
Opened 2021-01-27 21:06 UTC by ImranVirani

2021-01-27 22:15 UTC, orestisfl commented
What error do you get? It works fine for me.

2021-01-27 22:27 UTC, Airblader commented
Seems fair, though, rofi's manpage also lists it as a comma separated list.

2021-01-27 22:33 UTC, orestisfl commented
> Seems fair, though, rofi's manpage also lists it as a comma separated list.

Replacing the comma makes the `run` menu not show up in my machine.

2021-01-27 22:36 UTC, Airblader commented
Maybe the command needs to be quoted?

2021-01-27 22:45 UTC, ImranVirani commented
Exact error is:

ERROR: Received ConfigureNotify for unknown window 0x00600000
ERROR: Received ExposeEvent for unknown window 0x00600000
ERROR: Received ConfigureNotify for unknown window 0x00600000
ERROR: Expected one of these tokens: <end>, '[', 'move', 'exec', 'restart', 'reload', 'shmlog', 'debuglog', 'border', 'layout', 'append_layout', 'workspace', 'focus', 'kill', 'open', 'fullscreen', 'stick', 'split', 'floating', 'mark', 'unmark', 'resize', 'rename', 'nop', 'scratchpad', 'swap', 'title_format', 'mode', 'bar', 'gaps'

ERROR: Your command: exec rofi -modi drun run,-show drun ( There is an underline under -show drun

It also only worked when I changed bindcode to bindsym, and removed the comma. If the comma stays and bindcode is in place of bindsym no errors are shown.

2021-01-27 22:46 UTC, ImranVirani commented
It might be distro dependant? I'm using Arctix Linux, which is arch based if that helps.

2021-01-27 22:48 UTC, orestisfl commented
> Maybe the command needs to be quoted?

In the i3 config file? Yes, and that's how I use it in my config.

2021-01-27 22:51 UTC, ImranVirani commented
@orestisfl That might be it, the command is not commented by default in the keycodes file

2021-01-27 22:55 UTC, orestisfl requested changes
Also please update this file with the same changes: https://github.com/i3/i3/blob/next/etc/config

2021-01-27 22:55 UTC, orestisfl commented on etc/config.keycodes
> +# bindcode $mod+40 exec rofi -modi drun run -show drun
That should work:

```suggestion
# bindcode $mod+40 exec "rofi -modi drun,run -show drun"
```

2021-01-27 23:48 UTC, ImranVirani commented
Updated. Thanks for the help.

2021-01-28 15:41 UTC, orestisfl approved these changes

2021-01-29 15:20 UTC, merged