Move workspaces to multiple outputs
i3/i3 pull request #4338
Opened 2021-02-03 17:39 UTC by orestisfl

2021-02-05 08:13 UTC, Airblader requested changes

2021-02-05 08:13 UTC, Airblader commented on docs/userguide
>  ------------------------------------------------------------
nit: align the dashes with the new length of the syntax?

2021-02-05 08:13 UTC, Airblader commented on docs/userguide
> +If you specify more than one outputs, the container/workspace is cycled through
"more than one outputs" → "more than one output"

2021-02-05 08:13 UTC, Airblader commented on src/commands.c
> +                    /* This corrupts the outter loop but it is ok since we are
nit: outter → outer

2021-02-05 08:13 UTC, Airblader commented on testcases/t/543-move-workspace-to-multiple-outputs.t
> +#!perl
Do we already have test cases for a single output in the list, i.e. to make sure that this works as before?

2021-02-05 08:13 UTC, Airblader commented on docs/userguide
> +If you specify more than one outputs, the container/workspace is cycled through
We should also mention here that non-existing outputs are skipped.

2021-02-05 10:03 UTC, orestisfl commented on testcases/t/543-move-workspace-to-multiple-outputs.t
> +#!perl
Yes!

2021-02-05 18:46 UTC, Airblader approved these changes

2021-02-05 18:46 UTC, Airblader commented
@orestisfl Maybe squash once before merging?

2021-02-06 11:52 UTC, merged

2021-10-22 07:35 UTC, vincentbernat commented
It would be useful to also be able to use `focus output next`.

2021-10-22 13:01 UTC, orestisfl commented
Vincent, please open a new issue to track this