Share graphics context globally
i3/i3 pull request #4376
Opened 2021-03-10 17:40 UTC by psychon

Instead of creating a graphics context for every surface_t, this commit
adds a cache that allows to "remember" up to two GCs. Thus, the code
uses less GCs. When a GC from the cache can be used, this also gets rid
of a round-trip to the X11 server. Both of these are tiny, insignificant
savings, but so what?

Fixes: https://github.com/i3/i3/issues/3478
Signed-off-by: Uli Schlachter <psychon@znc.in>

-----

This adds a copy&paste duplicate of `get_visual_depth()` from `src/xcb.c` to `libi3. If you tell me what to do, I can clean this up again, but I was not really sure what the best option here is.

I tried testing the cache overflow by trying to create a window with a depth other than 24 or 32, but my X11 server does not offer any such visuals:
```
$ xdpyinfo| grep depth: | uniq
    depth:    24 planes
    depth:    32 planes
```
Also, initially I planned to use a `SLIST` for this and have the cache unlimited. After briefly staring at the macros, I went with a statically sized solution instead. Thus, there is now the possibility that a GC cannot be cached and is thus still owned by the `surface_t`.

2023-07-15 17:22 UTC, orestisfl commented on libi3/draw_util.c
> +        xcb_free_gc(conn, surface->gc);
What happens after you free the gc that is used in other surfaces?

2023-07-16 07:52 UTC, psychon commented on libi3/draw_util.c
> +        xcb_free_gc(conn, surface->gc);
Uhm... Sorry, but I don't quite get the question...?

I just re-read the diff and `owns_gc` is only set by `get_gc()`. That function only ever sets `owns_gc = true` when nothing else references the GC. Put differently: If the resulting GC is saved in the cache (either already before or during the call to `get_gc()`), `owns_gc = false`. If the resulting GC is only referenced by the `draw_util_surface`, then `owns_gc = true`.

So, to try to answer the question: If this were to free a GC that is also used in other `draw_util_surface`s, that would be bad. But I don't think that can possibly happen.

2023-07-16 19:22 UTC, orestisfl requested changes
Thank you, and sorry for the delayed review

2023-07-16 19:22 UTC, orestisfl commented on libi3/draw_util.c
> +        xcb_free_gc(conn, surface->gc);
Correct, never mind my comment

2023-07-16 19:22 UTC, orestisfl commented on libi3/draw_util.c
> +static uint16_t get_visual_depth(xcb_visualid_t visual_id) {
I would delete this function from xcb.c and move it to libi3 to not have duplicated code

2023-07-16 19:22 UTC, orestisfl commented on libi3/draw_util.c
> +} gc_cache[2] = {
I feel like in i3 we are sticking too much in primitive data structures even though we can take advantage of more advanced ones, e.g. this could have been implemented more easily with [glib's hashtable](https://docs.gtk.org/glib/struct.HashTable.html) and glib is already a dependency.

I am not really requesting that you re-write this, just an observation. You can ignore this comment.

2023-07-16 19:22 UTC, orestisfl commented on libi3/draw_util.c
> +static struct {
This static struct can live entirely inside the `get_gc` function since it's only referenced there.

2023-07-17 16:36 UTC, psychon commented on libi3/draw_util.c
> +} gc_cache[2] = {
Yeah, I didn't use much glib so far. I quickly looked at the link and then decided to go with `You can ignore this comment`. :sweat_smile:

2023-07-17 16:40 UTC, psychon commented
I rebased this on `next` (had some conflicts) and addressed the comments.

I am not entirely sure, but the following comments now seems outdated:
```c
    if (surface->owns_gc) {
        /* NOTE: This function is also called on uninitialised surface_t instances.
         * The x11 error from xcb_free_gc(conn, XCB_NONE) is silently ignored
         * elsewhere.
         */
        xcb_free_gc(conn, surface->gc);
    }
```
`uninitialised` cannot really mean "contains arbitrary garbage". That sounds like a recipe for crashes. So I guess this means zero-initialised. In that case, `owns_gc` should be `false` and I just made this error case go away.

However, this is just a guess and I don't have the time right now to dig deeper, so I am just mentioning this here and keeping things otherwise the way they already were.

2023-07-20 22:02 UTC, orestisfl requested changes
Thanks, couple of last things

2023-07-20 22:02 UTC, orestisfl commented on libi3/draw_util.c
> +         */
> I rebased this on `next` (had some conflicts) and addressed the comments.
> 
> I am not entirely sure, but the following comments now seems outdated:
> 
> ```c
>     if (surface->owns_gc) {
>         /* NOTE: This function is also called on uninitialised surface_t instances.
>          * The x11 error from xcb_free_gc(conn, XCB_NONE) is silently ignored
>          * elsewhere.
>          */
>         xcb_free_gc(conn, surface->gc);
>     }
> ```
> 
> `uninitialised` cannot really mean "contains arbitrary garbage". That sounds like a recipe for crashes. So I guess this means zero-initialised. In that case, `owns_gc` should be `false` and I just made this error case go away.
> 
> However, this is just a guess and I don't have the time right now to dig deeper, so I am just mentioning this here and keeping things otherwise the way they already were.

The comment mentions `XCB_NONE` so that's what I imagine it means, not garbage. I've played around and we can still get errors on the free but they happen in `next` as well, we can continue ignoring them for now. I think we can remove the comment as it seems misleading now.

```suggestion
```

2023-07-20 22:02 UTC, orestisfl commented on libi3/draw_util.c
> +    xcb_void_cookie_t gc_cookie = xcb_create_gc_checked(conn, gc, drawable, 0, NULL);
```suggestion
    /* The drawable is only used to get the root and depth, thus the gc is not
     * tied to the drawable and it can be re-used from different drawables. */
    xcb_void_cookie_t gc_cookie = xcb_create_gc_checked(conn, gc, drawable, 0, NULL);
```

I came up with this while trying to understand why this is safe to do e.g. when creating a gc from a drawable that is later freed. If my comment is correct, maybe we can include it for further context to readers?

2023-07-22 06:16 UTC, psychon commented on libi3/draw_util.c
> +    xcb_void_cookie_t gc_cookie = xcb_create_gc_checked(conn, gc, drawable, 0, NULL);
Done.

"Definitive answer" seems to come from the X11 protocol reference manual: https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#requests:CreateGC

>  The gcontext can be used with any destination drawable having the same root and depth as the specified drawable [...]

2023-07-22 08:23 UTC, orestisfl approved these changes
Thank you

2023-07-22 08:24 UTC, merged