docs: fix broken link to Pango documentation
i3/i3 pull request #4411
Opened 2021-04-23 23:13 UTC by alarsyo

Looks like `/stable/` no longer automatically points to the latest version, so I linked to the "homepage" instead. :/

2021-04-24 06:09 UTC, Airblader requested changes
Thanks for noticing this and raising a PR! I think it'd be useful to still link to the correct place, so maybe we should just link to the (current) latest version. The exact version hopefully doesn't matter too much anyway. Can you change the PR that way? Thanks!

2021-04-26 14:14 UTC, alarsyo commented
Should be alright now :)

2021-04-26 14:29 UTC, Airblader approved these changes

2021-04-26 14:29 UTC, merged

2021-04-26 14:29 UTC, Airblader commented
Thank you!