Implement include config directive
i3/i3 pull request #4420
Opened 2021-05-13 15:19 UTC by stapelberg

The implementation [uses wordexp(3) just like sway](https://github.com/i3/i3/issues/1197#issuecomment-226844106)

Thanks to jajm [for their implementation at](https://github.com/jajm/i3/commit/bb55709d0aa0731f7b3c641871731a992ababb1a)

This required refactoring the config parser to be re-entrant
(no more global state) and to return an error instead of dying.

In case a file cannot be opened, i3 reports an error but proceeds with the
remaining configuration.

All files that were successfully included are displayed in `i3 --moreversion`.

One caveat is i3 config file variable expansion, see the note in the userguide.

fixes #4192

2021-05-13 16:02 UTC, kgilmer commented
Happy to see this <3.  Do you plan to ship an updated default config file with a wildcard matching scheme similar to [the Sway solution](https://git.sr.ht/~sircmpwn/dotfiles/tree/master/item/.config/sway/config#L175)?

2021-05-13 16:07 UTC, kgilmer commented on docs/userguide
> +* You cannot use (in the parent file) a variable that was defined within an included file.
Is it actually a parent/child relationship here or simply order of evaluation of the partials?

2021-05-13 16:10 UTC, Airblader commented
I'll hopefully get around to reviewing this tomorrow. I'll +1 adding wildcard includes for distributions like Regolith.

One concern coming to mind is duplicate binding handling. There's a case to be made that overrides should be allowed across files, but perhaps just not within the same file?

2021-05-14 06:53 UTC, stapelberg commented on docs/userguide
> +* You cannot use (in the parent file) a variable that was defined within an included file.
Can you elaborate on which nuance you’re trying to get at?

Since the parent is always evaluated before any children, the parent always comes first in the order of evaluation.

Perhaps we should mention that variables defined in one file can be used in a sibling file (e.g. `include a*.conf` with a00.conf and a01.conf, you can set a variable in a00.conf and use it in a01..conf).

2021-05-14 06:57 UTC, stapelberg commented
> I'll +1 adding wildcard includes for distributions like Regolith.

What makes Regolith special in this regard?

How would these wildcard includes need to look like?

Just `include /etc/i3/config.d/*.conf` to handle system-level additions, or also `include config.d/*.conf` to handle user-level additions? Or would we leave the latter up to the user to set up?

> One concern coming to mind is duplicate binding handling. There's a case to be made that overrides should be allowed across files, but perhaps just not within the same file?

Perhaps we loosen the duplicate binding restriction in a separate step later on? It’s not clear to me that we necessarily need to, or why bindings are a special case compared to other directives?

2021-05-14 07:05 UTC, Airblader commented
> What makes Regolith special in this regard?

They currently need to ship a customized, self maintained default config. With wildcards they could instead just ship additional files but leave the default config from i3 in place.

> Or would we leave the latter up to the user to set up?

I don't feel too strongly about those, but don't see a harm in adding that either. The system level ones will just make life for packagers easier who want to offer customized i3 packages.

> or why bindings are a special case compared to other directives?

If anything, they're a special case right now, since we don't check for duplicate directives for anything other than bindings. So overwriting any directives is totally fine, just bindings cause issues. 
Again, for something like Regolith that probably makes this feature less useful. But perhaps someone from Regolith can comment more on that, @kgilmer?

2021-05-14 10:17 UTC, orestisfl requested changes

2021-05-14 10:17 UTC, orestisfl commented on src/config_directives.c
> +            // version in potentially very short include fragments:
Nit: `/* */` comments :)

2021-05-14 10:17 UTC, orestisfl commented on src/config_directives.c
> +                break;
Since `parse_file` is an `int` we are missing a `default` case here, a compiler might complain

2021-05-14 10:17 UTC, orestisfl commented on src/config_directives.c
> +                // fallthrough
```suggestion
                /* fallthrough */
```

2021-05-14 10:17 UTC, orestisfl commented on src/config.c
> +    }
It seems that the root file can be included by an `include` directive. This seems to fix that:

```suggestion
    }
    
    file = scalloc(1, sizeof(IncludedFile));
    file->path = sstrdup(resolved_path);
    TAILQ_INSERT_TAIL(&included_files, file, files);
    
```

2021-05-14 10:17 UTC, orestisfl commented on docs/userguide
> +include ~/.config/i3/`hostname`.conf
Which is the code that implements the backtick functionality? What happens (and what should happen?) when the command fails?

2021-05-14 10:27 UTC, orestisfl commented on docs/userguide
> +include ~/.config/i3/`hostname`.conf
Ok, it's [`wordexp`](https://man7.org/linux/man-pages/man3/wordexp.3.html)

2021-05-14 10:29 UTC, orestisfl commented on src/config_directives.c
> +            // version in potentially very short include fragments:
Btw, we should add `include` in here: https://github.com/i3/i3/blob/9db03797da3cea5dc6898adc79a68ba4523a409c/src/config_parser.c#L638-L644

2021-05-14 13:51 UTC, stapelberg commented on src/config_directives.c
> +            // version in potentially very short include fragments:
Comment changed. We already have `include` in the code you link.

2021-05-14 13:51 UTC, stapelberg commented on src/config_directives.c
> +                break;
Done.

2021-05-14 13:52 UTC, stapelberg commented on src/config_directives.c
> +                // fallthrough
Done.

2021-05-14 13:52 UTC, stapelberg commented on src/config.c
> +    }
Good catch, done!

2021-05-14 13:53 UTC, stapelberg commented on docs/userguide
> +include ~/.config/i3/`hostname`.conf
Stdout of the command is relevant, the exit code is ignored.

If a command fails without producing any output, the backticks evaluate to an empty string.

2021-05-14 13:53 UTC, stapelberg commented on docs/userguide
> +include ~/.config/i3/`hostname`.conf
Also added a test to exercise this behavior.

2021-05-14 15:50 UTC, kgilmer commented on docs/userguide
> +* You cannot use (in the parent file) a variable that was defined within an included file.
Surely, I can elaborate..my question comes from reasoning about i3 partial load order and how, say, keybinding state in i3 may be mutated as a consequence of evaluation of one partial to another.  I've noticed in another thread in the PR that keybinding overrides may not be allowed (as-is i3 throws an error if the same key is bound to within the config file).  In the case that overrides are allowed from partial to partial, it becomes important to be able to understand partial evaluation order.  If internally it's evaluated as list this is easier than a tree structure, but I guess really I just need to know that the sort on config file partial is stable/consistent.

This all stems from the desire for Regolith to conform to baseline configuration as much as possible, as to not hinder users from being able to take advantage of all of the existing community work in customizations etc..  Regolith (by choice) does not conform to the standard i3 keybindings (in particular window navigation, dmenu/rofi launch).  In order for Regolith to keep it's variance we either need to be able to override default keybindings in a partial, or just launch i3 in the Xsession initialization with a non-standard config file as is done now.  Thinking through this, overriding keybindings in partials may end up being more trouble/confusion to end users, as they would need to understand this overriding behavior as well as partial loading heuristics (the root problem being that the entire config file merged would have conflicting declarations).

2021-05-14 15:59 UTC, stapelberg commented on docs/userguide
> +* You cannot use (in the parent file) a variable that was defined within an included file.
> If internally it's evaluated as list this is easier than a tree structure, but I guess really I just need to know that the sort on config file partial is stable/consistent.

There is no sorting going on. i3 is recursively parsing configuration files in the order in which you tell it to.

I guess that maps to a “tree” in your terminology.

2021-05-14 16:01 UTC, stapelberg commented
Sounds like we should tie the binding duplicate check to the file in which the binding is defined.

2021-05-14 16:03 UTC, kgilmer commented
> They currently need to ship a customized, self maintained default config AFAIK. With wildcards they could instead just ship additional files but leave the default config from i3 in place.

Yes,  this would be a good change if Regolith was able to use stock i3 config file(s).  A concern I have is possible difficult in users understanding why a given keybinding was mapped if there are multiple partials that all may set that keybinding.  For example, the stock i3 may map the app launcher to `<super> d` but Regolith would override this to be `<super> space`.  Generally speaking, if overrides are allowed, to be useful for Regolith we'd need Update and Delete in addition to Create.

> If anything, they're a special case right now, since we don't check for duplicate directives for anything other than bindings. So overwriting any directives is totally fine, just bindings cause issues.
> Again, for something like Regolith that probably makes this feature less useful. But perhaps someone from Regolith can comment more on that, @kgilmer?

I may be missing some simpler approaches but as I see it now, if we allow overrides across partials, I'm guessing that i3 will undergo a general regression relating to the complexity of the i3 config file.  Because before config partials, a keybinding is a keybinding.  But after partials, a keybinding is whatever keybinding expression was evaluated last across the ordered set of evaluated partials.  Partials as a feature us a huge benefit to Regolith, and using a custom config is relatively minor.  That said I may be missing some simple way that keybinding overrides can be implemented that does not increase general complexity in the i3 config file.

2021-05-14 16:06 UTC, stapelberg commented
> Generally speaking, if overrides are allowed, to be useful for Regolith we'd need Update and Delete in addition to Create.

Currently, every directive behaves like Upsert: update if present, and insert if not present yet.

Can you explain why you need Delete?

2021-05-14 16:07 UTC, Airblader commented
> Generally speaking, if overrides are allowed, to be useful for Regolith we'd need Update and Delete in addition to Create.

That's a good point.

I think changing the behavior for duplicate binding detection might not be a good idea. An alternative could be modularizing the default config to eg move bindings into a separate file. Then packagers could just not ship that one file and instead their own bindings, which allows all additions and deletions. I'm not sure we'd want to do that with the default config, though.

2021-05-14 16:08 UTC, kgilmer commented
Let me say all that again in another way: I presently don't see a way of being able to re-use a stock i3 config file in Regolith without having to introduce conflicting keybinding statements (plus either/or partial semantics or some kind of "unbind" operator) in partials. These conflicts I expect would confuse some users.

2021-05-14 16:10 UTC, kgilmer commented
> Can you explain why you need Delete?

A contrived example is that stock i3 uses `<super> d` for drun.  Regolith uses `<super> space`.  I would want` <super> d` to do nothing. (in practice `<super> d` in Regolith maps to gnome display settings, but I'm guessing there are actual cases like this presently).

2021-05-14 16:13 UTC, kgilmer commented
> I think changing the behavior for duplicate binding detection might not be a good idea. An alternative could be modularizing the default config to eg move bindings into a separate file. Then packagers could just not ship that one file and instead their own bindings, which allows all additions and deletions. I'm not sure we'd want to do that with the default config, though.

Yes, in my mind weighing the options i3 would want to maintain continuity of the existing monolithic config file (because it is simple, easy to reason about, and well known) rather than the top level file just being a skeleton and breaking partials out for each ["config category" as I have done in a PoC for Regolith 2.0](https://github.com/regolith-linux/regolith-i3-config/tree/master/partials).

2021-05-14 16:16 UTC, stapelberg commented
> A contrived example is that stock i3 uses `<super> d` for drun. Regolith uses `<super> space`. I would want` <super> d` to do nothing. (in practice `<super> d` in Regolith maps to gnome display settings, but I'm guessing there are actual cases like this presently).

Right, I think we’ll have to declare this use-case out of scope.

Config parsing with includes is “additive” or “overwrite-only”, no directive (neither key bindings nor others like e.g. focus_follows_mouse) supports expressing “reset this back to default”.

2021-05-14 17:54 UTC, Airblader approved these changes
LGTM! This will surely make a lot of people happy.

2021-05-15 08:12 UTC, stapelberg commented on docs/userguide
> +* You cannot use (in the parent file) a variable that was defined within an included file.
Added a note in the userguide about this.

2021-05-15 08:15 UTC, stapelberg commented
Pushed an updated version where I also introduce the `--remove` flag for `bindsym` and `bindcode`.

These can be used to overwrite or remove key bindings, which is useful from included config files.

Duplicate key binding checking happens after each file was parsed, i.e. on the return path of the recursion. I don’t think we need any changes to duplicate key binding checking after all.

I added basic tests for this, but please give it a shot and see if it works as expected.

This should cover most use-cases, and I think implementing it for key bindings as a special case makes sense. For the other config directives, we can consider similar behavior on a case-by-case basis, and I expect most will work fine without modifications.

2021-05-15 08:18 UTC, Airblader commented
I'm a bit confused about that change. I thought we didn't want to support this use case? I'm not actually a fan of a flag to remove bindings.

2021-05-15 08:22 UTC, stapelberg commented
> I thought we didn't want to support this use case? 

Initially, I thought one could at least overwrite key bindings, but then I realized that’s not currently possible.

Hence, I came around on the need to change something about key bindings.

> I'm not actually a fan of a flag to remove bindings.

What’s your concern about this flag? The implementation is pretty straight-forward, and use-cases such as “use the standard i3 config, but overwrite that one key binding” become much easier to express.

2021-05-15 08:29 UTC, Airblader commented
I think removing bindings "somewhere down the line" adds significant mental complexity. For a configuration format something like "undo this configuration I just did above" feels awkward; configs are static, which is what sets config and commands apart.

Allowing to statically remove statically added bindings from within the config, but not allowing adding or removing for_window directives at runtime, for example, sounds illogical to me and hard to justify (yes I'm aware they're two different things). There's no way to statically remove for_window directives, nor bar blocks etc.

Such a flag feels less like a solution and more like a workaround to me.

2021-05-15 08:36 UTC, Airblader commented
Another note on this: removing previous bindings is sensitive to the inclusion order.

2021-05-15 08:44 UTC, stapelberg commented
> I think removing bindings "somewhere down the line" adds significant mental complexity.

I agree that `include` directives in general, and overwriting semantics in particular make configuration more complex.

I suppose there are ways to counter that complexity with easier debugging. Perhaps even switching from recursively evaluating config files to actually concatenating them first might be a change that helps in that regard, but I think that can be done in a separate pull request.

> For a configuration format something like "undo this configuration I just did above" feels awkward;

For multi-file configs, this is a standard feature. See for example systemd’s drop-in config files, where the `ExecStart=` directive is a list, and if you want to overwrite that list from a drop-in config file, you need to empty it (“remove” it in our terminology) explicitly first, e.g.:
```
% cat /etc/systemd/system/robustirc-bridge.service.d/override.conf 
[Service]
ExecStart=
ExecStart=/usr/bin/robustirc-bridge -socks= -listen=localhost:6637 -network=robustirc.net
```
```
% systemctl status robustirc-bridge
● robustirc-bridge.service - RobustIRC bridge
     Loaded: loaded (/usr/lib/systemd/system/robustirc-bridge.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/robustirc-bridge.service.d
             └─override.conf
```

> configs are static, which is what sets config and commands apart.

I don’t think of them in terms of “static” (and “dynamic”?), but rather in terms of evaluation time: the configuration is applied when loading/reloading it, whereas commands are applied/interpreted/executed whenever needed.

> Allowing to statically remove statically added bindings from within the config, but not allowing adding or removing for_window directives at runtime, for example, sounds illogical to me and hard to justify (yes I'm aware they're two different things).

Amending the config at runtime is a separate feature, I think.

> There's also no way to statically remove for_window directives, nor bar blocks etc. for that matter.

Yes, it might make sense to eventually add support to these, too, if that turns out to be a popular user request.

> Another note on this: removing previous bindings is sensitive to the inclusion order.

Yes, but so are many other directives that already effectively have overwrite semantics, such as changing the font with the `font` directive.

Also note that the variable `set` command (and `set_from_resource`) use upsert semantics already.

2021-05-15 09:21 UTC, orestisfl requested changes

2021-05-15 09:21 UTC, orestisfl commented on src/bindings.c
> +    if (remove != NULL && command == NULL) {
This `if` is unnecessary, the comment can stay

2021-05-15 09:21 UTC, orestisfl commented on src/bindings.c
> +    }
Not necessarily a strictly better way to write this but WDYT about this:

```suggestion

if (remove) {
    bool found = false;
    Binding *bind;
    TAILQ_FOREACH (bind, mode->bindings, bindings) {
        if (binding_same_key(bind, new_binding)) {
            if (command){
                /* --remove specified with command: find existing key binding
                 * and replace it, or append if no existing key binding found. */
                TAILQ_REPLACE(mode->bindings, bind, new_binding, bindings);
                found = true;
                break;
            } else {
                /* --remove specified without command: remove the existing key
                 * binding (if any) without replacement. */
                TAILQ_REMOVE(mode->bindings, bind, bindings);
                return NULL;
            }
        }
    }

    if (!command){
        return NULL;
    } else if (!found){
        TAILQ_INSERT_TAIL(mode->bindings, new_binding, bindings);
    }
}
```

2021-05-15 09:21 UTC, orestisfl commented on src/bindings.c
> +    /* If bind is NULL, current has to be NULL, too (see previous conditional).
I think here you are referring to old variables, `bind`, `current`

2021-05-15 09:21 UTC, orestisfl commented on src/config_directives.c
> +                break;
I was thinking more in the lines of an assertion failure maybe? The code doesn't return something different.

Alternatively, I might prefer to introduce an enum for readability here instead.

2021-05-15 09:21 UTC, orestisfl commented on testcases/t/313-include.t
> +is(launch_get_border($config), 'none', 'no border');
Wouldn't this test work best if we checked that both cases of the `--remove` keybinding work as intended (in a different file -- we already have binding test code)? I.e., a. remove and test that the keybinding does nothing b. remove and replace and test that the new command is executed.

2021-05-15 10:28 UTC, stapelberg commented on testcases/t/313-include.t
> +is(launch_get_border($config), 'none', 'no border');
Good point, done.

2021-05-15 10:28 UTC, stapelberg commented on src/config_directives.c
> +                break;
Done.

2021-05-15 10:28 UTC, stapelberg commented on src/bindings.c
> +    /* If bind is NULL, current has to be NULL, too (see previous conditional).
Done.

2021-05-15 10:29 UTC, stapelberg commented on src/bindings.c
> +    }
Thanks for the suggestion.

I think I prefer the current version because of its early return pattern, which keeps indentation and code path complexity at a minimum.

2021-05-15 10:29 UTC, stapelberg commented on src/bindings.c
> +    if (remove != NULL && command == NULL) {
I think it’s cleaner to express all the different cases like this.

2021-05-15 16:38 UTC, Airblader commented
> For multi-file configs, this is a standard feature.

Even if we agree on that, we're not introducing a standard solution here but rather a different thing for every directive. For most you just overwrite the value, for bindings there's a special flag now. For bar blocks or for_window it isn't even clear what the syntax would look like.

All of this amounts to trying to special case something that probably doesn't warrant that complexity. For normal users, they can take care of this problem by more carefully designing their files. My original thought were packagers like Regolith, for which this would be useful, but for such a small use case I wouldn't want to add this level of complexity to the config.

Furthermore, we shouldn't treat the default config as a sacred thing that cannot be touched. Configuration exists to be changed. Users who want to remove a default binding can do so already.

> Amending the config at runtime is a separate feature, I think.

So is "remove a previously defined binding within the config". :-)

I really find it odd that we support CRUD in the config but not at runtime. As far as "if it's a popular user request" goes — the expectation that all config directives can be executed as commands at runtime is probably one of the top issues I see people run into. And wanting to change the runtime makes much more sense to me as well as it opens many scripting use cases. 

This flag, however, is just a bandaid to serve a single, and very small, use case, and doesn't even provide a full solution for other directives.

> Yes, but so are many other directives that already effectively have overwrite semantics

Overwriting requires no special syntax, though. If anything, the consistent way to handle this would then be to remove bindings if they're empty:

```
# unbind
bindsym $mod+r
```

But that'd still not provide a solution for things like for_window which by nature must be additive.

Overall I feel adding this flag (at this stage) is a mistake, because it is inconsistent, incomplete and its usecase doesn't justify added syntax, so as far as my vote goes I'd vote no.

2021-05-15 16:43 UTC, stapelberg commented
I don’t think it makes sense to introduce an `include` directive without a way to overwrite bindings. In my mind, bindings are the primary thing that most i3 users configure, and not a small niche use-case.

You don’t like the `--remove` flag and that’s fair. But do you have a suggestion for how to implement overwriting bindings instead?

If we don’t want additional syntax, we must remove the duplicate bindings check (because those then overwrite and aren’t duplicative).

Or are you saying you vote against the `include` directive altogether?

2021-05-15 16:47 UTC, Airblader commented
> Or are you saying you vote against the include directive altogether?

No, the directive is extremely useful and a big plus for users. I only vote against the flag to remove bindings.

> I don’t think it makes sense to introduce an include directive without a way to overwrite bindings.

I think most users will not be using this flag. They modularize their config into multiple files and load certain ones based on hostname etc. I don't think having to overwrite a previous binding is something most users will (have to do), instead they just won't define the binding in that environment to begin with.

The only two scenarios where a flag to delete a binding is useful in my mind is when trying to keep and extend the default config (which just isn't necessary) or for packagers like Regolith (which aren't a strong enough of a use case to justify this as they can just ship a modified default config).

2021-05-15 18:57 UTC, kgilmer commented
Having had a chance to think about the ramifications of this change a bit more, perhaps the ideal for Regolith (and maybe others) would be to have no default config file at all.  Rather, in the [Xsession init](https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/usr/bin/regolith-session-init#L54) have something like:

(assuming i3 has a capability to [read config from `stdin`](https://faq.i3wm.org/question/2566/is-there-a-way-to-read-the-i3-configuration-from-stdin/index.html)):
```bash
echo "include /etc/i3/conf.d/*; include /etc/regolith/i3/conf.d/*; include ~/regolith/i3/conf.d/*" | i3 -
```

or if config directory feature was exposed via commandline arguments, where `-D` represents one or more include statements:
```bash
i3 -D /etc/i3/conf.d/* -D /etc/regolith/i3/conf.d/* -D ~/regolith/i3/conf.d/*
```

My reasoning is to why this would be better than having an equivalent root config file w/ is:
1. A common hurdle for new users is knowing they have to restart i3 if they change the location of the config file.  Despite documentation this is probably one of the top 3 issues I've noticed Regolith users have.  (eg They copy the i3 into the user dir, make a change, refresh and don't see any difference.)
2. If there is no root file there is less of a change that an accidental change in the root breaks everything.  I think this is a weak reason but also the simplicity of "everything is a config partial".

(Please LMK if this not the right forum for me to discuss ideas like this, happy to move it somewhere else or keep to myself without any offense taken.)

2021-05-15 21:29 UTC, stapelberg commented
> I only vote against the flag to remove bindings.

I reverted that part of the pull request for now and added a section to the userguide about this restriction.

I’ll ask people over on the issue what they think, i.e. whether that works for their desired use-cases or not.

> My reasoning is to why this would be better than having an equivalent root config file w/ is:

Reading the config from stdin isn’t great ergonomics, I think, independent of whether it actually works or not (it does not work currently).

Having the config visible in a file is simpler to grasp.

> 1. A common hurdle for new users is knowing they have to restart i3 if they change the location of the config file.  Despite documentation this is probably one of the top 3 issues I've noticed Regolith users have.  (eg They copy the i3 into the user dir, make a change, refresh and don't see any difference.)

Unless overwrite the config path using the `-c` flag when starting i3, usually i3 should be discovering the config path from scratch on every `reload`. If that’s not what you’re seeing, please file a separate issue about that.

2021-05-17 08:07 UTC, orestisfl approved these changes

2021-05-17 08:23 UTC, orestisfl requested changes
`i3-msg -t get_config` is broken since `char *current_config` in `config_parser.c:893` only keeps the latest read file.

2021-05-19 05:25 UTC, orestisfl requested changes

2021-05-19 05:25 UTC, orestisfl commented on src/config_parser.c
> +        chdir(dir);
Here and in other `chdir`s, I get a warning: 

```
[78/139] Compiling C object i3.p/src_config_parser.c.o
../i3/src/config_parser.c: In function ‘parse_file’:
../i3/src/config_parser.c:873:9: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  873 |         chdir(dir);
      |         ^~~~~~~~~~
../i3/src/config_parser.c:1107:5: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1107 |     chdir(old_dir);
```

2021-05-19 16:10 UTC, stapelberg commented on src/config_parser.c
> +        chdir(dir);
Fixed, thanks.

2021-05-19 16:10 UTC, stapelberg commented
> `i3-msg -t get_config` is broken since `char *current_config` in `config_parser.c:893` only keeps the latest read file.

Fixed, thanks!

2021-05-23 08:20 UTC, stapelberg commented
Looks like we’re not going to get much more feedback here, so I suggest we merge what we have now and rely on users reporting issues before the release.

@orestisfl anything left to change or can you approve please?

2021-06-02 09:08 UTC, orestisfl requested changes
No strong opinion for me but what do you think about `GET_CONFIG` returning the full config, after includes instead of just the top level config?

2021-06-02 09:08 UTC, orestisfl commented on include/bindings.h
> +bool binding_same_key(Binding *a, Binding *b);
Does this need to be exported? It seems to be used only in `bindings.c`.

2021-06-02 09:17 UTC, orestisfl requested changes

2021-06-02 09:17 UTC, orestisfl commented on src/config_parser.c
> +        (void)chdir(dir);
Sorry, it is doing it again:

```
../i3/src/config_parser.c: In function ‘parse_file’:
../i3/src/config_parser.c:873:15: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  873 |         (void)chdir(dir);
      |               ^~~~~~~~~~
../i3/src/config_parser.c:1108:11: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1108 |     (void)chdir(old_dir);
      |           ^~~~~~~~~~~~~~
```

Maybe since we are assuming the call succeeds, we should accompany it with an `assert`?

2021-06-02 15:16 UTC, stapelberg commented on include/bindings.h
> +bool binding_same_key(Binding *a, Binding *b);
Done.

2021-06-02 15:16 UTC, stapelberg commented on src/config_parser.c
> +        (void)chdir(dir);
Changed it to report an error when the call fails.

2021-06-02 15:18 UTC, stapelberg commented
> No strong opinion for me but what do you think about `GET_CONFIG` returning the full config, after includes instead of just the top level config?

Yeah, improving what `GET_CONFIG` returns is something I thought about, but I’d like to tackle that in a separate pull request. This PR gives us an implementation to use, the next PR can change the implementation to make possible better `GET_CONFIG` output without changing the behavior otherwise.

2021-06-02 17:07 UTC, orestisfl requested changes

2021-06-02 17:07 UTC, orestisfl commented on src/config_parser.c
> +            ELOG("chdir(%s) failed: %s\n", dir, strerror(errno));
Shouldn't we `return PARSE_FILE_FAILED;` here?

2021-06-02 17:07 UTC, orestisfl commented on src/config_parser.c
> +        ELOG("chdir(%s) failed: %s\n", old_dir, strerror(errno));
I guess continuing here without a hard error breaks the expectations of other parts of the code but on the other hand we don't want i3 to exit with an error during a reload/restart.

This shouldn't really happen anyway.

2021-06-02 17:24 UTC, stapelberg commented on src/config_parser.c
> +            ELOG("chdir(%s) failed: %s\n", dir, strerror(errno));
No, I don’t think this error is grave enough to warrant aborting.

2021-06-02 17:24 UTC, stapelberg commented on src/config_parser.c
> +        ELOG("chdir(%s) failed: %s\n", old_dir, strerror(errno));
Yep. See above.

2021-06-02 17:25 UTC, stapelberg commented
@orestisfl can you approve so we can merge? We can always improve further later. Thanks :)

2021-06-02 18:09 UTC, orestisfl commented on src/config_parser.c
> +            ELOG("chdir(%s) failed: %s\n", dir, strerror(errno));
It can in theory mean that i3 reads configuration from the wrong files if for some reason this happens but the `open` call does not fail (and since `chdir` failing should always lead to `open` failing, we are practically only aborting in cases where the `open` would lead to aborting as well).

Since the configuration parsing is one place where i3 can execute arbitrary code, I would prefer if we were overly cautious about it.

2021-06-02 18:26 UTC, stapelberg commented on src/config_parser.c
> +            ELOG("chdir(%s) failed: %s\n", dir, strerror(errno));
Done.

2021-06-02 18:45 UTC, orestisfl approved these changes
Thanks!

2021-06-02 19:01 UTC, merged