Implement showing window icons in titlebar
i3/i3 pull request #4439
Opened 2021-06-03 08:01 UTC by stapelberg

This feature defaults to off, and can be turned on for individual windows,
or (with for_window) for all new windows. See the userguide change.

This commit is partially based on work by:

• Marius Muja
• mickael9
• Esteve Varela Colominas
• Bernardo Menicagli

fixes #905

2021-06-03 09:29 UTC, psychon approved these changes
:+1: but I left some minor comments anyway

2021-06-03 09:29 UTC, psychon commented on include/data.h
> +    int icon_height;
No idea if it really makes any difference, but wouldn't it be easier to keep the icon around as a `cairo_surface_t*`? One variable instead of three and the drawing code would not have to re-create the surface all the time.

This might also have performance benefits (implications?), but I am not sure if they really make much of a difference:

If this is an image surface, cairo can upload the icon to the X11 server once and then keep that internally as a so-called snapshot on the image surface (so that later on cairo can directly see "ah, this image was already uploaded to the X11 server before. I can just re-use the pixmap").

It might also be possible to keep this directly as an xcb surface since the local image is not really needed ever again, but setting that up is slightly more complicated and has little gain, so dunno about this... (Well, one could create a cairo surface for the root window and then use `cairo_surface_create_similar(CAIRO_CONTENT_COLOR_ALPHA)` to create the xcb surface plus `cairo_surface_map_to_image()` to get an image surface to draw the pixel data to; cairo could then allocate the image surface's pixel data in shared memory which allows to upload the image "more easily".)

TL;DR: I am suggesting optimisations which make the code more complicated (I guess...?) and provide little benefit.

2021-06-03 09:29 UTC, psychon commented on parser-specs/commands.spec
> +    -> call cmd_title_window_icon($enable, 0)
Hm. The new `boolstr` and the code here duplicate the list of "true-ish" strings.

Could that be moved into the `.spec`? The parser could treat "title_window_icon on" and "title_window_icon off" as different... things and then directly call `cmd_title_window_icon` with `true`/`false`.

Edit: Only now do I see that `boolstr()` already existed before and you are only moving it around, so it might not make as much sense to move that parsing into the parser, I guess...

2021-06-03 09:29 UTC, psychon commented on src/commands.c
> +    }
Now I am even more convinced that more of this parsing should be moved into the command parser. The `enable` argument can just be removed and you can directly call this with `padding=0` or `-1`.

2021-06-03 09:29 UTC, psychon commented on src/window.c
> +        const uint32_t cur_height = prop_value[1];
Why not moving `cur_width` and `cur_height` up above the other two variables? That way, `prop_value[0]` could be replaced with the more readable `cur_width` in the computation (and same with `cur_height`).

2021-06-03 09:29 UTC, psychon commented on src/window.c
> +                          width < pref_size || height < pref_size))) {
Since I have been staring at this for a moment, I think:
- This needs a comment how icons are chosen.
- The current logic is:
  - Assuming quadratic icons: Use the smallest icon with width & height both `>= pref_size`. If no such icons exists, pick the first icon (because of the `len == 0` check; shouldn't it rather pick the largest icon instead for this case?)
  - Non-quadratic icons: It's complicated and depends on the order of the icons. Hopefully the precise behaviour is not important and it is hard to define something meaningful anyway...

2021-06-03 09:29 UTC, psychon commented on src/window.c
> +        a = (data[2 + i] >> 24) & 0xff;
Suggestion for (a tiny bit of) improved readability: Add an extra variable `uint32_t pixel = data[2 + i];` and use that in the following lines (but feel free to ignore this if you want).

2021-06-03 09:29 UTC, psychon commented on src/window.c
> +        win->icon[i] = (a << 24) | (r << 16) | (g << 8) | b;
As I recently learned in cairo, this is technically undefined behaviour if `a >= 0x80`:
- `a << 24` is promoted to `int`
- assuming `sizeof(int) == 4`, you are shifting a one into the sign bit, i.e. triggering signed overflow.

I am not 100% sure I got this right (is `uint8_t << int` really promoting to `int`?), but in cairo we had a large patch adding `(uint32_t) a << 24` to a lot of places.

2021-06-03 09:39 UTC, orestisfl commented
As a top level comment, I would like to make sure that we explicitly touch on the fact that this is a net-positive feature for most users that is going to be hidden behind a per-window command. The alternatives are:

1. Don't make this configurable, globally on
2. Make this opt-out globally with a config directive
3. Make this opt-in globally with a config directive
4. Make this opt-out per window with a command
5. Make this opt-in per window with a command

This PR implements `#5`. @stapelberg, @Airblader is this your favorite option?

I am fine with all options.

2021-06-03 09:49 UTC, Airblader commented
I'd disqualify (2) and (4) immediately because this is a pretty significant change to look&feel and we've always tried to avoid noticable changes unless a user opts in. This obviously also rules out (1).

Experience has taught me that (3) almost never works out, and sooner or later people want per-window options. This also enables users to roll more complex scenarios themselves, like doing it for the focused window, certain workspaces, etc.

There are more alternatives, such as combining a global directive with per-window overrides, which is kind of what we'd "traditionally" do. But really that creates more overhead than it is worth.

In summary, I think the solution chosen here is fine. I do think that we should consider adding a quality of life `all` match criterion, though. Using an always-matching regex isn't very user friendly and I've come across users many times who didn't know how to do it.

2021-06-03 10:03 UTC, orestisfl commented
Yeah now that I am using it, it does feel disruptive to the usual look & feel of i3.

2021-06-03 18:41 UTC, stapelberg commented
Thanks everyone for the thoughtful and nuanced discussion and code review! :)

I think the for_window + command approach is a proven pattern that should cover all use-cases with minimal changes, as you also concluded.

Will update this PR soon

2021-06-03 21:19 UTC, psychon commented on src/window.c
> +                          width < pref_size || height < pref_size))) {
Actually... why is this looking at the width of the icon at all? Since this chooses an icon based on the height of the titlebar, only the height of the icon should matter.

2021-06-05 18:27 UTC, stapelberg commented on src/window.c
> +        const uint32_t cur_height = prop_value[1];
Done.

2021-06-05 18:27 UTC, stapelberg commented on src/window.c
> +        a = (data[2 + i] >> 24) & 0xff;
Done.

2021-06-05 18:27 UTC, stapelberg commented on src/window.c
> +        win->icon[i] = (a << 24) | (r << 16) | (g << 8) | b;
Hmm, the following test program:
```c
/*
 * vim:ts=4:sw=4:expandtab
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdbool.h>
#include <stdint.h>

int main() {
  printf("sizeof(int) = %u\n", sizeof(int)); // 4
  uint8_t r, g, b, a;
  r = 23;
  g = 42;
  b = 5;
  a = 0x80;
  uint32_t icon = (a << 24) | (r << 16) | (g << 8) | b;
  printf("icon = %u\n", icon);
  uint32_t fixed = (uint32_t)((((uint32_t)(a)) << 24) | ((uint32_t)r << 16) | ((uint32_t)g << 8) | (uint32_t)b);
  printf("fixed = %u\n", fixed);
}
```

prints:
```
% gcc -m32 -o undef undefined.c -Wall && ./undef
sizeof(int) = 4
icon = 2149001733
fixed = 2149001733
```

So that shouldn’t be required, or at least it’s not the full story? Was the patch only needed for a specific architecture/environment perhaps?

2021-06-05 18:27 UTC, stapelberg commented on src/window.c
> +                          width < pref_size || height < pref_size))) {
Yeah, I agree this is pretty confusing. I factored out the conditions into descriptively named bools, which makes it a little easier to understand.

I also implemented your suggestion regarding chosing the largest icon when there is no icon that has at least the preferred size.

I suppose looking at the width as well means we only consider quadratic icons? Probably a good defense in depth strategy, I suppose…

2021-06-05 18:27 UTC, stapelberg commented on include/data.h
> +    int icon_height;
Thanks, that’s a great tip!

Please take another look at the updated code, and particularly at the memory management bits (freeing the data / destroying the surface).

2021-06-05 18:27 UTC, stapelberg commented on parser-specs/commands.spec
> +    -> call cmd_title_window_icon($enable, 0)
This alternative way of expressing the logic in the `commands.spec` file:
```
  '1', 'yes', 'true', 'on', 'enable', 'active'
    -> call cmd_title_window_icon(true, 0)
  '0', 'no', 'false', 'off', 'disable', 'inactive'
    -> call cmd_title_window_icon(false, 0)
```

…doesn’t work because we need to keep track of the enable state on the parser stack, so that state `TITLE_WINDOW_ICON_PADDING` can use the enable state, too.

Another alternative, introducing a new token type is something I want to avoid because then we’d need special casing for users to be able to use e.g. `enable`, `active`, etc. in a string context. That’s much more complex than avoiding the duplication here.

It follows that we need to duplicate the strings between the `.spec` file and the C code.

Now, could we move this duplication from `commands.c` to `commands_parser.c` and `generate-command-parser.pl`? Absolutely. But that’s a cleanup that’s probably better done in a separate pull request to keep commits small, and the git history clean and bisectable.

2021-06-05 18:27 UTC, stapelberg commented on src/commands.c
> +    }
See above.

2021-06-05 18:36 UTC, stapelberg commented
All done, CI now passing, too!

Please take another look

2021-06-05 19:47 UTC, psychon commented on src/window.c
> +        win->icon[i] = (a << 24) | (r << 16) | (g << 8) | b;
Try enabling UBSan (that's also the context for cairo: It was just done to silence UBSan):
```
$ gcc -fsanitize=undefined f.c && ./a.out 
sizeof(int) = 4
f.c:15:22: runtime error: left shift of 128 by 24 places cannot be represented in type 'int'
icon = 2149001733
fixed = 2149001733
```

2021-06-05 19:49 UTC, psychon commented on src/window.c
> +        win->icon[i] = (a << 24) | (r << 16) | (g << 8) | b;
See:
- https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/147
- https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/149

2021-06-05 19:51 UTC, stapelberg commented on src/window.c
> +        win->icon[i] = (a << 24) | (r << 16) | (g << 8) | b;
Ah, thanks! Done.

2021-06-06 11:15 UTC, psychon commented on parser-specs/commands.spec
> +    -> call cmd_title_window_icon($enable, 0)
Okay, I have zero clue about the capabilities of the parser here. I somehow thought this would be easy to do, sorry.

2021-06-06 11:28 UTC, psychon requested changes
Thanks! I only left one and a half suggestions.

The icon selection seems way more readable now, although I have to admit that I did not look at it carefully.

2021-06-06 11:28 UTC, psychon commented on src/window.c
> +        free(data);
Dunno if it makes this much easier / more readable, but you can get a callback from cairo when a surface is finished / destroyed. This can be used to automatically free the data:
```c
static cairo_user_data_key_t free_data;
win->icon = cairo_image_surface_create_for_data(the same as the already existing code);
cairo_surface_set_user_data(win->icon, &free_data, icon, free);
```
That way, you could just `cairo_surface_destroy` the surface without having to do the dance about also freeing the data.

2021-06-06 11:28 UTC, psychon commented on src/window.c
> +    FREE(win->icon);
Now that this is a cairo surface, this should be `cairo_surface_destroy`. You also need to
- either do the already existing dance of checking if this is non-`NULL` and also free the data
- go with my other suggestion with `cairo_surface_set_user_data` so that cairo also frees the underlying data through a callback.

2021-06-06 12:36 UTC, stapelberg commented on src/window.c
> +        free(data);
Done, thanks!

2021-06-06 12:36 UTC, stapelberg commented on src/window.c
> +    FREE(win->icon);
Done, good catch!

2021-06-12 21:03 UTC, stapelberg commented
Is this good to go? We need 1 approving review please :)

2021-06-12 22:34 UTC, orestisfl approved these changes
Sorry, LGTM and I've been using it for a while

2021-06-13 06:35 UTC, merged