handlers.c: send an "output" event on monitor configuration change
i3/i3 pull request #4469
Opened 2021-08-01 16:13 UTC by vincentbernat

When adding/removing a monitor, the outputs are likely to be modified.
Send an IPC event "output", like when there is a screen configuration
change.

Signed-off-by: Vincent Bernat <vincent@bernat.ch>

2021-09-09 16:41 UTC, orestisfl approved these changes
Seems to work in my case.

The only other "output" event seems to be in `handlers.c:handle_screen_change`.

@Airblader WDYT?

2021-09-10 05:17 UTC, Airblader commented
Fine with me, however we need to add this to the release notes, too. @vincentbernat Can you add an entry in `RELEASE-NOTES-next` for this?

2021-09-10 05:44 UTC, vincentbernat commented
OK, added!

2021-09-10 05:48 UTC, Airblader requested changes
Thank you! Also thanks for catching that mistake and fixing it, but could we have that as a separate commit? Would be appreciated!

2021-09-10 05:48 UTC, Airblader commented on RELEASE-NOTES-next
> +This is i3 v4.20. This version is considered stable. All users of i3 are
Thanks for catching this mistake. Could you maybe split this into a separate commit? This would be worth keeping even if we somehow had to revert the PR (as unlikely as it might be).

2021-09-10 06:05 UTC, vincentbernat commented on RELEASE-NOTES-next
> +This is i3 v4.20. This version is considered stable. All users of i3 are
Done.

2021-09-10 06:06 UTC, Airblader approved these changes
Thank you!

2021-09-10 06:09 UTC, merged