i3-dmenu-desktop: ignore duplicate files and directories
i3/i3 pull request #4565
Opened 2021-10-06 16:07 UTC by stapelberg

This is required when e.g. mpv is installed in the NixOS global system
environment *and* in the user environment.

Standalone reproducer:
```
mkdir -p test1/share/applications test2/share
ln -svf /usr/share/applications/i3.desktop test1/share/applications
ln -svf $PWD/test1/share/applications test2/share
export XDG_DATA_DIRS='test1/share:test2/share'
i3-dmenu-desktop
```
fixes #4522

2021-10-06 16:09 UTC, Airblader approved these changes

2021-10-07 13:59 UTC, orestisfl requested changes
Thanks!

Needs a release note item

2021-10-07 21:25 UTC, stapelberg commented
Done. Also rebased onto next, GitHub Actions now passes

2021-10-07 21:38 UTC, orestisfl approved these changes

2021-10-07 21:38 UTC, merged