Keep each release note in a single file
i3/i3 pull request #4610
Opened 2021-10-19 20:27 UTC by orestisfl

To avoid annoying merge conflicts.

~python~ perl script is provided for convenience and simple format checking in
PRs.

2021-10-20 07:03 UTC, Airblader reviewed
Doesn't this require changes to release.sh so that there are steps to generate the changelog and also to delete the change files again?

2021-10-20 08:02 UTC, orestisfl commented
These usually need some final grooming by @stapelberg. Maybe I can add a reminder in `release.sh`?

2021-10-21 06:42 UTC, stapelberg commented
When preparing the release notes for v4.20, I actually appreciated the fact that I could use `git blame` to quickly navigate to each PR that was important enough to be mentioned.

If we split the release notes into separate files, that is no longer possible.

But, more importantly: if we use separate files, I don’t see why we not just use `git log` to build the release notes (possibly annotating commits that should not be mentioned, or possibly annotating commits with the specific message that they should produce in the release notes). Using separate files just seems duplicative to me in that regard?

2021-10-21 06:56 UTC, Airblader commented
If we go with commits and annotating them in some way, I would vote for just adopting a well-established standard like [conventional commits](https://www.conventionalcommits.org/).

2021-10-21 07:08 UTC, stapelberg commented
Conventional commits doesn’t cover release notes, though, or at least I couldn’t see anything about that?

I’m used to having a RELNOTES field in the commit message or similar.

2021-10-21 07:11 UTC, Airblader commented
With conventional commits, a changelog is usually generated directly from the commit message headline. If you want the release notes to be orthogonal to that, then yes, conventional commits AFAIK doesn't cover that.

2021-10-21 07:16 UTC, stapelberg commented
Yes, in general I’d like the release notes to be orthogonal, otherwise we’re back to square one where I manually compile the release notes based on git history.

2021-10-22 06:16 UTC, orestisfl commented
The script can probably call git-blame and find the PR if we want.

My problem with the commit-based approach is that it's a bit more cryptic and that there is no real way to edit the release notes during development, at best we can append release notes with empty commits.

2021-10-22 15:17 UTC, stapelberg requested changes
https://about.gitlab.com/blog/2018/07/03/solving-gitlabs-changelog-conflict-crisis/ comes to a similar conclusion, so I’m willing to try the one-file-per-change approach.

2021-10-22 15:17 UTC, stapelberg commented on release-notes/generator.py
> +#!/usr/bin/env python3
I know it’s annoying, but can you rewrite this in Perl for consistency with the rest of the code base? I’d like to keep the number of languages involved at a minimum. Let me know if you get stuck and I can try to give a pointer.

2021-10-23 08:51 UTC, orestisfl commented
Switch to Perl

Updated to find the PR if possible. Not 100% robust but I doubt there is a better way that doesn't involve fetching information from github.

That could be done like this: 
``` shell
$ curl 'https://api.github.com/repos/i3/i3/commits/b7af69cba8027ab7c36678c921136d85f1e7242b/pulls' | jq -r .[0].html_url
https://github.com/i3/i3/pull/4617
```

2021-11-04 16:27 UTC, stapelberg requested changes

2021-11-04 16:27 UTC, stapelberg commented on release-notes/generator.pl
> +    opendir my $dir, $dirpath or die "Cannot open directory $dirpath: $!";
It’s probably a little easier to use https://perldoc.perl.org/File::Find instead of readdir.

2021-11-04 16:27 UTC, stapelberg commented on release-notes/changes/0-example
> +Acquire the WM_Sn selection when starting as required by ICCCM
Can you put in some unicode here? Special characters and/or emoji perhaps. Just to make sure the generator is UTF-8 clean.

2021-11-04 16:27 UTC, stapelberg commented on release-notes/generator.pl
> +        $s = $s . '  • ' . $content . "\n" . $url . "\n";
I’m not sure if we want to always include the URL in the output.

It’s useful for me when compiling the release notes (for clarifications if needed),
but I’m not sure others will appreciate the URLs as much (or just see them as line noise).

Maybe we could use a flag for this?

2021-11-04 17:57 UTC, orestisfl commented on release-notes/generator.pl
> +    opendir my $dir, $dirpath or die "Cannot open directory $dirpath: $!";
Is it easy to restrict only to the first directory level?

2021-11-04 18:14 UTC, orestisfl commented on release-notes/changes/0-example
> +Acquire the WM_Sn selection when starting as required by ICCCM
The examples are for contributors.

Copied it over with emojis for testing

2021-11-04 18:14 UTC, orestisfl commented on release-notes/generator.pl
> +        $s = $s . '  • ' . $content . "\n" . $url . "\n";
A bit overkill IMO since this script is only for us and the CI but added a flag

2021-11-05 08:38 UTC, stapelberg commented on release-notes/generator.pl
> +    opendir my $dir, $dirpath or die "Cannot open directory $dirpath: $!";
Can’t see a way to do that easily. We can probably stick to readdir then.

2021-11-05 08:38 UTC, stapelberg approved these changes

2021-11-05 09:36 UTC, merged