Docs: Testsuite: Grammar
i3/i3 pull request #4618
Opened 2021-10-22 12:21 UTC by Jonta

2021-10-22 12:58 UTC, orestisfl requested changes
Thanks ;)

2021-10-22 12:58 UTC, orestisfl commented on docs/testsuite
> +It is targeted at developers who have not necessarily been doing testing before
I think present perfect would be even simpler here: "who haven't necessarily done testing before or..."

2021-10-22 13:02 UTC, Jonta commented on docs/testsuite
> +It is targeted at developers who have not necessarily been doing testing before
I agree

2021-10-23 08:42 UTC, orestisfl commented on docs/testsuite
> +It is targeted at developers who have not necessarily been doing testing before
So, do you want to update your PR? :)

2021-10-24 15:39 UTC, Jonta commented on docs/testsuite
> +It is targeted at developers who have not necessarily been doing testing before
@orestisfl Done

2021-10-24 15:45 UTC, orestisfl approved these changes

2021-11-01 20:42 UTC, merged