Refuse to start without IPC socket
i3/i3 pull request #4647
Opened 2021-11-02 19:33 UTC by psychon

This change was (basically) suggested by @orestisfl in
https://github.com/i3/i3/pull/4638#issuecomment-958093518

Testing done:
```
$ I3SOCK=/dev/null DISPLAY=:2 LC_ALL=C build/i3
bind(): Address already in use
i3: Could not create the IPC socket: Address already in use
```
Signed-off-by: Uli Schlachter <psychon@znc.in>

----

Do you want me to also get rid of the `else` branch? The way the code is now, `ipc_io` has a smaller scope, which I like, so I'd at most replace it with `{ }` (so just dropping the `else`).

2021-11-02 19:35 UTC, orestisfl requested changes
```diff
diff --git a/src/main.c b/src/main.c
index c73601da6..e8b7228bb 100644
--- a/src/main.c
+++ b/src/main.c
@@ -683,6 +683,11 @@ int main(int argc, char *argv[]) {
         else
             config.ipc_socket_path = sstrdup(config.ipc_socket_path);
     }
+    /* Create the UNIX domain socket for IPC */
+    int ipc_socket = create_socket(config.ipc_socket_path, &current_socketpath);
+    if (ipc_socket == -1) {
+        die("Could not create IPC socket: %s\n", config.ipc_socket_path);
+    }
 
     if (config.force_xinerama) {
         force_xinerama = true;
@@ -988,15 +993,10 @@ int main(int argc, char *argv[]) {
 
     tree_render();
 
-    /* Create the UNIX domain socket for IPC */
-    int ipc_socket = create_socket(config.ipc_socket_path, &current_socketpath);
-    if (ipc_socket == -1) {
-        ELOG("Could not create the IPC socket, IPC disabled\n");
-    } else {
-        struct ev_io *ipc_io = scalloc(1, sizeof(struct ev_io));
-        ev_io_init(ipc_io, ipc_new_client, ipc_socket, EV_READ);
-        ev_io_start(main_loop, ipc_io);
-    }
+    /* Listen to the IPC socket for clients */
+    struct ev_io *ipc_io = scalloc(1, sizeof(struct ev_io));
+    ev_io_init(ipc_io, ipc_new_client, ipc_socket, EV_READ);
+    ev_io_start(main_loop, ipc_io);
 
     /* Chose a file name in /tmp/ based on the PID */
     char *log_stream_socket_path = get_process_filename("log-stream-socket");
```

Moved it up a bit, and removed the `else` branch

2021-11-02 20:10 UTC, psychon commented
Done. I skipped the `\n` from the error message since something already adds a new line to it. Commit message is updated.

Feel free to just "steal" this PR and open your own PR if more changes are necessary and I am too slow / if that's easier for you. Good night.

2021-11-02 22:13 UTC, orestisfl approved these changes

2021-11-02 22:13 UTC, merged

2021-11-02 22:14 UTC, orestisfl commented
Changes needs release note after https://github.com/i3/i3/pull/4610

2021-11-03 15:32 UTC, psychon commented
Thanks for merging.

I'd suggest to add a new GitHub label for "still needs release notes entry" to track this. When the way forward for release notes is decided and all release notes were written, that label can be deleted again.