Implement title_window_icon toggle
i3/i3 pull request #4710
Opened 2021-12-02 13:57 UTC by pstray

An implentation of the feature request in i3/i3#4709

2021-12-02 14:13 UTC, orestisfl requested changes
Thanks, LGTM

You'll also need to include:

- [x] A test case in `t/314-window-icon-padding.t`
- [x] A new line in a new file in `release-notes/changes`

2021-12-03 11:26 UTC, pstray commented
Not sure why those tests failed...

2021-12-03 11:44 UTC, orestisfl requested changes

2021-12-03 11:44 UTC, orestisfl commented on src/commands.c
> +        if (strcmp(enable, "toggle") == 0) {
```suggestion
        if (enable != NULL && strcmp(enable, "toggle") == 0) {
```

2021-12-03 11:44 UTC, orestisfl commented on src/commands.c
> +            current->con->window_icon_padding = current->con->window_icon_padding >= 0 ? -1 : padding;
`padding` can be `-1` here. In that case, you should use `0`.

2021-12-03 12:23 UTC, pstray commented on src/commands.c
> +            current->con->window_icon_padding = current->con->window_icon_padding >= 0 ? -1 : padding;
yes, it most probably will too... as boolstr("enable") return 0.  I'll fix

2021-12-03 12:37 UTC, pstray commented
Fixed it by actually saving the old value instead of setting it directly.

2021-12-03 14:16 UTC, orestisfl requested changes

2021-12-03 14:16 UTC, orestisfl commented on testcases/t/314-window-icon-padding.t
> +
Can you make sure that the toggle tests actually test the exact padding value? E.g. start with -1, set to 3, toggle to -1, toggle to 3

2021-12-03 14:16 UTC, orestisfl commented on src/commands.c
> +            current->con->window_icon_padding = -(current->con->window_icon_padding + 1);
That's nice but I think that if `padding` is set it should have precedence. So, if enabling and `padding > 0`, use that value.

This will be more consistent with `border toggle <n>`

2021-12-03 14:58 UTC, pstray commented on src/commands.c
> +            current->con->window_icon_padding = -(current->con->window_icon_padding + 1);
there is currently no way of toggling _and_ setting the padding.  But it if it is already set with `padding 3px`, then the toggle will keep that padding, and not reset it to 0 as the previous version did.

2021-12-03 16:31 UTC, pstray commented on testcases/t/314-window-icon-padding.t
> +
Added test for toggling after padding is set

2021-12-03 16:38 UTC, pstray commented on src/commands.c
> +            current->con->window_icon_padding = -(current->con->window_icon_padding + 1);
Thus, `on` sets to `0`, `off` sets to `-1`, 'padding Npx` set so `N`, and `toggle` flips between no padding (some negative value) and padding by storing the padding as '-(N+1)' when toggling.  If the padding was 0, it will become -1, if it was -1, it will become 0, and 3 will become -4, and -4 will become 3.

2021-12-03 17:05 UTC, orestisfl commented on src/commands.c
> +            current->con->window_icon_padding = -(current->con->window_icon_padding + 1);
It's not so difficult to adjust. Here is a MWE:

```diff
diff --git a/parser-specs/commands.spec b/parser-specs/commands.spec
index 89b258730..486f20dd3 100644
--- a/parser-specs/commands.spec
+++ b/parser-specs/commands.spec
@@ -468,7 +468,9 @@ state TITLE_FORMAT:
 state TITLE_WINDOW_ICON:
   'padding'
     -> TITLE_WINDOW_ICON_PADDING
-  enable = '1', 'yes', 'true', 'on', 'enable', 'active', '0', 'no', 'false', 'off', 'disable', 'inactive', 'toggle'
+  enable = 'toggle'
+    -> TITLE_WINDOW_ICON_PADDING
+  enable = '1', 'yes', 'true', 'on', 'enable', 'active', '0', 'no', 'false', 'off', 'disable', 'inactive'
     -> call cmd_title_window_icon($enable, 0)
 
 state TITLE_WINDOW_ICON_PADDING:
diff --git a/src/commands.c b/src/commands.c
index ad2b6cc20..5fc4440fd 100644
--- a/src/commands.c
+++ b/src/commands.c
@@ -2068,7 +2068,8 @@ void cmd_title_format(I3_CMD, const char *format) {
  *
  */
 void cmd_title_window_icon(I3_CMD, const char *enable, int padding) {
-    if (enable != NULL && !boolstr(enable)) {
+    const bool is_toggle = (enable && strcmp(enable, "toggle") == 0);
+    if (enable != NULL && !is_toggle && !boolstr(enable)) {
         padding = -1;
     }
     DLOG("setting window_icon=%d\n", padding);
@@ -2076,13 +2077,22 @@ void cmd_title_window_icon(I3_CMD, const char *enable, int padding) {
 
     owindow *current;
     TAILQ_FOREACH (current, &owindows, owindows) {
-        DLOG("setting window_icon for %p / %s\n", current->con, current->con->name);
-        if (enable != NULL && strcmp(enable, "toggle") == 0) {
-            /* Set to negative of (current value+1) to keep old padding when toggling */
-            current->con->window_icon_padding = -(current->con->window_icon_padding + 1);
+        if (is_toggle) {
+            const int current_padding = current->con->window_icon_padding;
+            if (padding > 0) {
+                if (current_padding < 0) {
+                    current->con->window_icon_padding = padding;
+                } else {
+                    current->con->window_icon_padding = -(padding + 1);
+                }
+            } else {
+                /* Set to negative of (current value+1) to keep old padding when toggling */
+                current->con->window_icon_padding = -(current_padding + 1);
+            }
         } else {
             current->con->window_icon_padding = padding;
         }
+        DLOG("Set window_icon for %p / %s to %d\n", current->con, current->con->name, current->con->window_icon_padding);
 
         if (current->con->window != NULL) {
             /* Make sure the window title is redrawn immediately. */
```

WDYT?

2021-12-06 07:38 UTC, pstray commented on src/commands.c
> +            current->con->window_icon_padding = -(current->con->window_icon_padding + 1);
The C code seems good to me.

2021-12-06 08:50 UTC, pstray commented on src/commands.c
> +            current->con->window_icon_padding = -(current->con->window_icon_padding + 1);
Not sure checking for enable != NULL is really needed.  Seems none of the other similar function do :)  But better safe than sorry i guess :grin:

2021-12-11 11:11 UTC, orestisfl requested changes
Thanks! I left some final nitpicks

2021-12-11 11:11 UTC, orestisfl commented on src/commands.c
> +    bool is_toggle = 0;
```suggestion
    bool is_toggle = false;
```

2021-12-11 11:11 UTC, orestisfl commented on src/commands.c
> +            is_toggle = 1;
```suggestion
            is_toggle = true;
```

2021-12-11 11:11 UTC, orestisfl commented on testcases/t/314-window-icon-padding.t
> +is(window_icon_padding($tmp), -4, 'window_icon_padding toggled to -4');
Let's not test for implementation details

```suggestion
ok(window_icon_padding($tmp) < 0, 'window_icon_padding toggled off');
```

2021-12-11 11:11 UTC, orestisfl commented on testcases/t/314-window-icon-padding.t
> +is(window_icon_padding($tmp), -6, 'window_icon_padding toggled off, save 5px as -6');
Same

```suggestion
ok(window_icon_padding($tmp) < 0, 'window_icon_padding toggled off');
```

2021-12-11 11:11 UTC, orestisfl commented on testcases/t/314-window-icon-padding.t
> +
Let's toggle with 5px to make sure it toggles to the correct amount

```suggestion

cmd 'title_window_icon toggle 5px';
is(window_icon_padding($tmp), 5, 'window_icon_padding toggled on to 4px');

cmd 'title_window_icon toggle 5px';
ok(window_icon_padding($tmp) < 0, 'window_icon_padding toggled off');

```

2021-12-11 11:11 UTC, orestisfl commented
Finally, please squash all commits into one before we can merge this.

2021-12-11 13:21 UTC, pstray commented
Added some fixes to comments and doc, and squashed it all.

2021-12-11 13:33 UTC, orestisfl approved these changes
Thank you!

2021-12-11 13:33 UTC, merged