fix and enhancement: Add i3bar option to not unhide on urgency (#4196, #5100)
i3/i3 pull request #5101
Opened 2022-09-01 01:12 UTC by gavine99

Closes #5100
Possibly closes #4196
Provides an i3bar option to stop unhiding i3bar when a window/workspace becomes urgent.
Includes documentation updates.

2022-09-20 15:44 UTC, orestisfl requested changes
Fine with this change overall

2022-09-20 15:44 UTC, orestisfl commented on docs/ipc
> +dont_unhide_for_urgent (boolean)::
A double negative is not a great configuration name.

IMO `show_on_urgent` reads better

2022-09-20 15:44 UTC, orestisfl commented on i3bar/src/xcb.c
> +                        unhide = true;
```suggestion
                    if (!config.dont_unhide_for_urgent) {
                        unhide = true;
                     }
```

2022-09-21 00:05 UTC, gavine99 commented on docs/ipc
> +dont_unhide_for_urgent (boolean)::
Agreed. I've pushed a new commit with the user-facing config option named as you suggested. docs updated too.

2022-09-21 06:08 UTC, orestisfl requested changes

2022-09-21 06:08 UTC, orestisfl commented on i3bar/src/xcb.c
> +                    if (!config.dont_unhide_for_urgent) {
I think this would also read better if it was named `show_on_urgent`

2022-09-21 06:08 UTC, orestisfl commented on include/configuration.h
> +     * default when initializing with zero. */
This needs updating as well

2022-09-21 06:10 UTC, orestisfl commented
Also, I don't see how this can fix #4196

2022-09-23 21:53 UTC, gavine99 commented on i3bar/src/xcb.c
> +                    if (!config.dont_unhide_for_urgent) {
ok. i changed the name throughout and defaulted it's value to true to maintain backwards compatibility

2022-09-23 21:53 UTC, gavine99 commented on include/configuration.h
> +     * default when initializing with zero. */
done

2022-09-23 22:05 UTC, gavine99 commented
> Also, I don't see how this can fix #4196

I had the same problem as that issue - bar re-showing when focus changed across monitor - and this PR stops it occurring. I believe that issue is actually caused because those people had an urgent window.  Good to get feedback from those users when they get version with this PR I guess.

2023-01-26 19:39 UTC, closed without merging