Fix top border resizing registered on tiled windows
i3/i3 pull request #5378
Opened 2023-01-16 18:30 UTC by slyshot

I noticed click+drag wasn't working on the top border of my tiled windows.
Unlike the other checks for where the mouse is clicked, it reference decoration. This commit makes it reference the borders like the other ones.

Thanks.

2023-01-18 12:20 UTC, orestisfl commented
This will probably conflict with

```
tiling_drag titlebar
```

2023-01-18 15:09 UTC, slyshot commented
ah, so put my new code in an `else` (or `else if (dest == CLICK_BORDER)`) to deal with both cases?

2023-04-22 16:32 UTC, orestisfl requested changes
Sorry for the delay. It seems your change is fine as it is.

Can you add some release notes for this change?

```shell
echo 'fix top border resizing on tiling windows' > release-notes/bugfixes/1-top-border-resize
git add release-notes/bugfixes/1-top-border-resize
```

2023-05-05 12:15 UTC, orestisfl approved these changes

2023-05-05 12:15 UTC, merged