Push artifacts only on next branch
i3/i3 pull request #5388
Opened 2023-01-22 18:25 UTC by orestisfl

2023-01-22 18:50 UTC, stapelberg commented on .github/workflows/main.yml
>      - name: build dist tarball
The dist tarball should always be built, even on pull requests (not just on the next branch)

2023-01-23 07:38 UTC, stapelberg requested changes

2023-01-23 07:38 UTC, stapelberg commented on .github/workflows/main.yml
>          docker pull ${{ env.BASENAME }} || ./travis/docker-build-and-push.sh ${{ env.BASENAME }} travis/travis-base.Dockerfile
docker-build-and-push.sh needs the DOCKER_ environment variables set so that it can push an updated version to the docker registry if needed. So please re-add the DOCKER_* variables to env: in line 19-21.

2023-01-23 07:56 UTC, Airblader commented on .github/workflows/main.yml
> +    if: github.ref == 'refs/heads/next'
Just double checking, this doesn't need to run for stable?

2023-01-23 08:03 UTC, stapelberg commented on .github/workflows/main.yml
> +    if: github.ref == 'refs/heads/next'
Correct, the autobuilder repositories only contain versions built from the `next` branch

2023-01-23 16:39 UTC, stapelberg approved these changes

2023-01-23 16:39 UTC, merged