Start i3 with a systemd service, if systemd is running and the service is loaded.
i3/i3 pull request #5591
Opened 2023-07-23 02:44 UTC by davidsansome

The systemd service activates `graphical-session.target` which in turn may activate other useful services such as the ssh-agent.

Fixes #5186

2023-10-12 17:39 UTC, Thaodan commented on systemd/i3-session.service
> +ExecStart=i3
Units usually use absolute paths for exec.
Should it be `@bindir@/i3`?

2023-10-17 18:13 UTC, Thaodan commented on systemd/i3-session.service
> +ExecStart=i3
```suggestion
ExecStart=i3
ExecReload=/usr/bin/i3-msg reload
```
In case the user want's to reload i3.

2023-12-29 22:19 UTC, faivirol reviewed
With this PR, replacing autostart scripts with services becomes feasible. I would add documentation about something like this:

```
[Unit]
Description=picom
BindsTo=i3@%i.service
After=i3@%i.service

[Service]
Environment=DISPLAY=%i
ExecStart=picom <args>

[Install]
WantedBy=i3@.service
```

Placed at `$XDG_CONFIG_HOME/systemd/user/picom.service`, it could then be enabled with `systemctl --user enable picom@` .

Alternatively, if sticking with the current service in the PR and not implementing instances, a simpler service like this could be used:

```
[Unit]
Description=picom
BindsTo=i3.service
After=i3.service

[Service]
ExecStart=picom <args>

[Install]
WantedBy=i3.service
```

The enabling would then also be without the at sign.

2023-12-29 22:19 UTC, faivirol commented on libexec/i3-session-start
If run a second time before the first is done, it will hang and wait for the same service. If not implementing support for multiple instances, a check and message for if the service is already running would at least show that the single instance limit is intended.

2023-12-29 22:19 UTC, faivirol commented on systemd/i3-session.service
> +[Service]
`Slice=session.slice` should be set in this case according to [`systemd.special`](https://www.freedesktop.org/software/systemd/man/latest/systemd.special.html#session.slice)

2023-12-29 22:19 UTC, faivirol commented on systemd/i3-session.service
Where does the service get `DISPLAY` and `XAUTHORITY` from? I can get it to work using `systemctl --user import-environment DISPLAY XAUTHORITY` in `.xinitrc` or adding `ENVIRONMENT=...` to the service, but I don't see how the service can work as is, although I might be missing something.

Although I don't often have two instances open, it does happen. My suggestion is to make the unit into a template and use the instance variable like `Environment=DISPLAY=%i`. This will support multiple instances and nonstandard `DISPLAY` values, making `i3-session-start` a drop-in replacement for running `i3`.

As for `XAUTHORITY`, asking the user to run/script `systemctl --user import-environment XAUTHORITY` before `i3-session-start` seems like a good choice since it is global for a user/systemd user instance (unlike `DISPLAY`), although a fallback to `~/.Xauthority` would probably be enough for most. For reference, [Arch already sets `XAUTHORITY` this way](https://unix.stackexchange.com/a/653101), although it is only [suggested in a note](https://wiki.archlinux.org/title/Xinit#xinitrc) that you actually include this in your user's `.xinitrc`.

2023-12-29 22:36 UTC, faivirol commented on systemd/i3-session.service
> +[Service]
Actually, this might not be the best since it seems like all processes i3 spawns, including applications, then fall under the session slice.

2023-12-30 01:41 UTC, Thaodan commented
I think applications should be started by the session-manager not by the
window-manager.

I don't think ***@***.*** is needed as there wouldn't be more than one
windoww-manager in the session.
Using `Install=windwmanager.servcice` in i3.service and
`After=windowmanager.service` in picom.service would make the unit more
universal for e.g. upstreaming of the picom service file.

2023-12-30 13:26 UTC, faivirol commented
> I think applications should be started by the session-manager not by the
window-manager.

What do you mean by this?

> I don't think \*\*\*@\*\*\*.\*\*\* is needed as there wouldn't be more than one
windoww-manager in the session.

After sleeping on it, this sounds more reasonable. The extra complexity is probably not justifiable for such a niche case. Using `systemd --user import-environment DISPLAY` would remove the need to provide it through an instance variable or hardcode it. If a user needs to run multiple instances, they can always fall back to executing the `i3` binary directly.

I am curious though about how you provide `DISPLAY` and `XAUTHORITY` to the service you posted in #5186, @Thaodan. Did you use `import-environment` as well?

> Using `Install=windwmanager.servcice` in i3.service and
`After=windowmanager.service` in picom.service would make the unit more
universal for e.g. upstreaming of the picom service file.

Yep, seems obvious in hindsight. Although `graphical-session.target` works as well (for `BindsTo`, `After` and `WantedBy`), so I think that's better than creating a new `windowmanager.service` standard.

2023-12-30 14:49 UTC, Thaodan commented
faivirol ***@***.***> writes:

>> I think applications should be started by the session-manager not by the
> window-manager.
>
> What do you mean by this?
>
>> I don't think \*\*\*@\*\*\*.\*\*\* is needed as there wouldn't be more than one
> windoww-manager in the session.
>
> After sleeping on it, this sounds more reasonable. The extra
> complexity is probably not justifiable for such a niche case. Using
> `systemd --user import-environment DISPLAY` would remove the need to
> provide it through an instance variable or hardcode it. If a user
> needs to run multiple instances, they can always fall back to
> executing the `i3` binary directly.
>
> I am curious though about how you provide `DISPLAY` and `XAUTHORITY`
> to the service you posted in #5186, @Thaodan. Did you use
> `import-environment` as well?

I only used the existing session started by KDE. The KDE session starter
first sets up it's own config, runs env scripts and then also imports the
systemd environment:
https://invent.kde.org/plasma/plasma-workspace/-/blob/master/startkde/startplasma-x11.cpp?ref_type=heads#L78


>> Using `Install=windwmanager.servcice` in i3.service and
> `After=windowmanager.service` in picom.service would make the unit more
> universal for e.g. upstreaming of the picom service file.
>
> Yep, seems obvious in hindsight. Although `graphical-session.target`
> works as well (for `BindsTo`, `After` and `WantedBy`), so I think
> that's better than creating a new `windowmanager.service` standard.
It's the same technique used to have multiple units to provide the same
service such as a display-manager.

2024-07-06 14:40 UTC, kjkent commented on systemd/i3-session.service
> Where does the service get `DISPLAY` and `XAUTHORITY` from? 

`/etc/X11/xinit/xinitrc.d/50-systemd-user.sh` should be sourced by the user's `$XINITRC` (default `~/.xinitrc`, falling back to `/etc/X11/xinit/xinitrc` if neither is found), which is sourced by `startx`/`xinit`. The fallback `xinitrc` contains:

```Sh
# ...
# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
```
As per the [Arch Wiki](https://wiki.archlinux.org/title/Systemd/User#Environment_variables):

>Units started by user instance of systemd do not inherit any of the [environment variables](https://wiki.archlinux.org/title/Environment_variables) set in places like .bashrc etc. There are several ways to set environment variables for them ...

There's a bit in _2.1.1_ talking about `DISPLAY` and `XAUTHORITY` in particular.

I hope some of this is useful and not just stuff you already know!

2024-07-19 16:19 UTC, budRich commented
i3-session-start is a **bash** script (`[[ $? != 0 || "${UNIT_LOAD_STATE}" != "loaded" ]]`) . Use appropriate shbang: `#!/usr/bin/env bash` . Also as in discussion about needing environment variables, before `systemctl start --user --wait i3-session.service` you could do: `dbus-update-activation-environment --systemd DISPLAY XAUTHORITY` .

Also the service type can be changed to `notify` since i3 implements the feature (#4454).


```
[Service]
Type=notify
ExecStart=i3
ExecStopPost=/bin/systemctl --user stop --no-block graphical-session.target
```

I use ExecStopPost to shut down other graphical programs started by systemd gracefully when i3 stops.

In my experience (i have been starting i3 with systemd for years), there are more environment variables one probably want. **PATH**, without it, relative paths in the i3 config file will not be found f.i. `exec --no-startup-id dex --autostart --environment i3` (from the default config) (dexplain to a new user why to init programs need to be involved to start i3...)  

`dbus-update-activation-environment --systemd DISPLAY XAUTHORITY` in my personal setup is actually: `dbus-update-activation-environment --systemd --all` , which will import **all** environment variables to **systemd**. But this is not proper to do security wise.  

`systemctl --user import-environment DISPLAY XAUTHORITY` <- this command and `dbus-update-activation-environment --systemd DISPLAY XAUTHORITY` are equivalent i think.

You will **break** lots of peoples configs if they start i3 without access to the PATH environment variable, but you will also upset lots of people for **compromising security** if you do import the PATH environment variable. In my opinion this whole systemd stuff is headaches that the package maintainers could customize for their distros if they wanted to. I wouldn't be surprised if a large chunk of i3 user base doesn't even have systemd..

2025-12-12 21:29 UTC, stapelberg requested changes
This looks pretty good overall, but there are a few changes to make. Are you still active and interested in making these changes?

If not, I can take over this PR. Ideally, let me know with a short message please :)

2025-12-12 21:29 UTC, stapelberg commented on libexec/i3-session-start
> +systemctl start --user --wait i3-session.service
Can you import the environment variables here please? Depending on the Linux distribution, this is either already done by xsession, or required for things to work. (Doing it multiple times is not an issue.)

```bash
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY XAUTHORITY
fi
```

2025-12-12 21:29 UTC, stapelberg commented on systemd/i3-session.service
> +Type=exec
Use `Type=notify` here please so that i3 is fully started by the time `graphical-session.target` activates.

2025-12-12 21:29 UTC, stapelberg commented on systemd/i3-session.service
Thanks for digging this up! I added a comment on libexec/i3-session-start and am marking this one here resolved.

2025-12-12 21:29 UTC, stapelberg commented on systemd/i3-session.service
> +Before=graphical-session.target
I think we should add `Wants=xdg-desktop-autostart.target` as well. Then, we’ll also need to update the default config to not start `dex` for this purpose if `xdg-desktop-autostart.target` is active.

2025-12-12 21:29 UTC, stapelberg commented on systemd/i3-session.service
Why not just `i3.service`?

2025-12-12 21:29 UTC, stapelberg commented on systemd/i3-session.service
> +ExecStart=i3
Agreed, we should use `@BINDIR@/i3` here

2025-12-13 19:48 UTC, Thaodan commented
Michael Stapelberg ***@***.***> writes:

> @stapelberg requested changes on this pull request.
>
>
>> @@ -0,0 +1,11 @@
> +[Unit]
> +Description=i3 Session
> +
> +Requires=graphical-session-pre.target
> +After=graphical-session-pre.target
> +BindsTo=graphical-session.target
> +Before=graphical-session.target
> +
> +[Service]
> +Type=exec
>
> Use `Type=notify` here please so that i3 is fully started by the time `graphical-session.target` activates.

Does i3 tell systemd when its ready? As long as i3 doesn't do that the
notify type doesn't work.

>> @@ -0,0 +1,11 @@
> +[Unit]
> +Description=i3 Session
> +
> +Requires=graphical-session-pre.target
> +After=graphical-session-pre.target
> +BindsTo=graphical-session.target
> +Before=graphical-session.target
>
> I think we should add `Wants=xdg-desktop-autostart.target` as well. Then, we’ll also need to update the default config to not start `dex` for this purpose if `xdg-desktop-autostart.target` is active.

That's part of the session manager which would be something else.

> On systemd/i3-session.service:
>
> Why not just `i3.service`?

IMHO i3wm would be the best as i3 is kinda short and i3-session implies
something else. The window manager is only part of the puzzle the
session management starts after the window manager is active.

A good example how units for the sesson launch are split up are the KDE
systemd units I think.

2025-12-14 09:31 UTC, stapelberg commented
> Does i3 tell systemd when its ready? As long as i3 doesn't do that the notify type doesn't work.

Yes: https://github.com/i3/i3/pull/4454

> > I think we should add `Wants=xdg-desktop-autostart.target` as well. Then, we’ll also need to update the default config to not start `dex` for this purpose if `xdg-desktop-autostart.target` is active.
>
> That's part of the session manager which would be something else.

Tell me more about this please. Which other unit would that be part of? 

> > Why not just `i3.service`?
>
> IMHO i3wm would be the best as i3 is kinda short and i3-session implies something else. 

So what? :) Our binary is also called i3. I think i3.service is consistent.

> The window manager is only part of the puzzle the session management starts after the window manager is active. A good example how units for the sesson launch are split up are the KDE systemd units I think.

Which aspect of the KDE systemd unit organization specifically do you think we should make sure to have? Where can one find/inspect these units?

2025-12-14 18:07 UTC, stapelberg commented
I’m taking over this issue with PR https://github.com/i3/i3/pull/6547 and will close this one (thank you!).

2025-12-14 18:07 UTC, closed without merging

2025-12-15 12:07 UTC, Thaodan commented
Michael Stapelberg ***@***.***> writes:

> stapelberg left a comment (i3/i3#5591)
>
>> Does i3 tell systemd when its ready? As long as i3 doesn't do that
>> the notify type doesn't work.
>
> Yes: https://github.com/i3/i3/pull/4454

Oh I didn't notice thanks.

>> > I think we should add `Wants=xdg-desktop-autostart.target` as
>> > well. Then, we’ll also need to update the default config to not
>> > start `dex` for this purpose if `xdg-desktop-autostart.target` is
>> > active.
>>
>> That's part of the session manager which would be something else.
>
> Tell me more about this please. Which other unit would that be part of? 
>
>> > Why not just `i3.service`?
>>
>> IMHO i3wm would be the best as i3 is kinda short and i3-session
>> implies something else.
>
> So what? :) Our binary is also called i3. I think i3.service is consistent.

>> The window manager is only part of the puzzle the session management
>> starts after the window manager is active. A good example how units
>> for the sesson launch are split up are the KDE systemd units I
>> think.
>
> Which aspect of the KDE systemd unit organization specifically do you
> think we should make sure to have? Where can one find/inspect these
> units?

I answer to the 2nd and last comment in one.

The main aspect I think would make sense here is that each individual
part of the session startup has is own unit so that the organization
of processes can grouped under their own cgroup and that the startup
process is reflected into the units as it actually happening.

For example the session restore waits for the window manager to finnish
starting. The unit for said session restore can then be started
after which means systemd will make sure that i3 is active
and ready before starting it. As for example can be seen
in the KDE Session Manager (KSM) systemd unit:
https://invent.kde.org/plasma/plasma-workspace/-/blob/master/ksmserver/plasma-ksmserver.service.in

Personally I have this unit for picom which uses just that condition.
First my i3 unit:
# /home/bidar/.local/etc/systemd/user/i3wm.service
[Unit]
Description=A tiling window manager for X11
After=plasma-kcminit.service
PartOf=graphical-session.target
Documentation=man:i3(1)

[Service]
ExecStart=/usr/bin/i3 --replace
ExecReload=/usr/bin/i3-msg restart
Slice=session.slice
Restart=on-failure

[Install]
Alias=plasma-kwin_x11.service
Alias=window-manager.service

Note: the first install alias is so I can replace kwin
in the plasma session, it has nothing to do with this discussion.
Site note: I think that i3 is part of the graphical-session but not
executed before it, since for example Xorg has to be up before i3 can start.

# /home/bidar/.local/etc/systemd/user/picom.service
[Unit]
Description=Picom compositor fork
Documentation=man:picom(1)
After=window-manager.service
PartOf=graphical-session.target
# Don't try to restart after 60 seconds
StartLimitIntervalSec=60

[Service]
ExecStart=/usr/bin/picom
ExecReload=/usr/bin/killall picom
# Try to restart no matter how the process ended
Restart=always
# Restart in 5 second intervals
RestartSec=5
# Try to restart up to 3 times
StartLimitBurst=3

[Install]
Alias=compositor.service
WantedBy=graphical-session.target

The After= condition in the unit section of the file above
will make sure that picom isn't started before i3 has finished
starting up. 

The main point is that each stage of the session startup can be split up
in its own unit so that in addition to cgroup settings being applied to
correctly that there can be also no race conditions.

The final startup order could be something like this:

1. start-i3session program initializes basic settings, checks that x11
 is active, reads startup config, set xdg variables etc.
 Check KDE's start kde program for reference:
 https://invent.kde.org/plasma/plasma-workspace/-/blob/master/startkde/startplasma-x11.cpp

2. The start session program then calls systemd to active the
   i3-session.target which requires all the services/targets required
   for the i3 session.
3. Systemd starts i3-session target.
   Check the plasma-workspace target for reference:
   https://invent.kde.org/plasma/plasma-workspace/-/blob/master/startkde/systemd/plasma-workspace.target
4. Inside that target the services for actual session to startup run.
   i.e.
   1. Services which apply settings such as xsettingsd start.
   2. i3 wm starts
   3. Any background service that needs a window manager or should start
   after the window manager i.e. such as a compositor start.
   4. The session starts, restarts previous applications. Systemds
      xdg-deskto-autostart.target starts.
      If installed a program to restore the previous sessions window
      layout could start.

5. start-i3session waits for the session to end and cleans
   the session up after the user requests to logout.

How these steps exactly are executed doesn't matter but a small
wrapper/script program is essential I think to ensure that the
environment is cleanly setup, the session target is executed and the
session is cleaned up.

The systemd website goes into some of this process:
https://systemd.io/DESKTOP_ENVIRONMENTS/


The systemd units can be found in their respective package,
that kinda makes them hard to navigate at once.

This Github shows them:
https://github.com/search?q=org%3AKDE+.service.in&type=code

This blogpost goes in detail about the session startup process in KDE
with systemd:
https://blog.davidedmundson.co.uk/blog/plasma-and-the-systemd-startup/

I hope I have explained everything detailed but also didn't go
overboard.