Add support for _NET_WM_STATE_MAXIMIZED_{HORZ, VERT}
i3/i3 pull request #5840
Opened 2023-12-26 18:58 UTC by sethpollen

If a window occupies the entirety of its workspace vertically and/or horizontally, pass it the _NET_WM_STATE_MAXIMIZED_{HORZ, VERT} atom. This helps applications like Google Chrome draw the tab bar correctly and handle tab clicks correctly (see https://crbug.com/1495853).

This change is based on work from @yshui in https://github.com/i3/i3/pull/2380.

2024-01-20 21:47 UTC, orestisfl reviewed
Great, thanks, please make sure to update the changelog as well, see: https://github.com/i3/i3/blob/next/.github/CONTRIBUTING.md

e.g.
```
echo 'add support for _NET_WM_STATE_MAXIMIZED_{HORZ, VERT}' > release-notes/changes/2-net-wrm-state-maximized
```

2024-01-20 21:47 UTC, orestisfl commented on src/con.c
> +        return false;
Here and everywhere, please use curly brackets

```suggestion
    if (con->fullscreen_mode != CF_NONE) {
        return false;
    }
```

2024-01-21 04:35 UTC, sethpollen commented on src/con.c
> +        return false;
Done (I think I got them all)

2024-01-21 04:36 UTC, sethpollen commented
Thanks! I added `release-notes/changes/2-net-wrm-state-maximized`.

2024-01-21 20:30 UTC, orestisfl requested changes
Thanks, few final things

2024-01-21 20:30 UTC, orestisfl commented on include/con.h
> +/*
nitpick

```suggestion
/**
```

2024-01-21 20:30 UTC, orestisfl commented on include/con.h
> + */
nitpick

```suggestion
 * https://github.com/i3/i3/pull/2380.
 *
 */
```

2024-01-21 20:30 UTC, orestisfl commented on testcases/t/551-net-wm-state-maximized.t
> +   'tabbed layout maximizes all windows');
Would also be nice to add a test case for a layout like `H[T[a b] c]` (tabbed next to a normal window in horizontal layout)

2024-01-22 18:01 UTC, sethpollen commented on testcases/t/551-net-wm-state-maximized.t
> +   'tabbed layout maximizes all windows');
Done.

2024-01-22 18:02 UTC, sethpollen commented on testcases/t/551-net-wm-state-maximized.t
> +   'tabbed layout maximizes all windows');
(I added it at the end of the file)

2024-01-22 19:29 UTC, orestisfl approved these changes

2024-01-22 19:29 UTC, orestisfl commented on testcases/t/551-net-wm-state-maximized.t
> +   'winB and winC are split vertically, so they are not maximized vertically');
I am not going to request that you change it because it's a bit of a chore but these combined boolean statements are hard to debug once one of them fails. It would be much better to re-write them like:

```
ok(maximized_vert($winB), '...');
ok(!maximized_vert($winC), '...');
```

Going to merge now without this but if you feel like re-factoring it later, feel free to.

2024-01-22 19:34 UTC, merged

2024-01-24 05:52 UTC, sethpollen commented on testcases/t/551-net-wm-state-maximized.t
> +   'winB and winC are split vertically, so they are not maximized vertically');
Thanks! I sent https://github.com/i3/i3/pull/5875.