smart_borders: Deprecate option
i3/i3 pull request #5889
Opened 2024-01-28 14:42 UTC by orestisfl

This had pretty much identical behaviour to hide_edge_borders which made it confusing. The `hide_edge_borders smart_no_gaps` implementation has an extra check which fixes #5406.

Fixes #5406

2024-01-29 07:44 UTC, stapelberg requested changes

2024-01-29 07:44 UTC, stapelberg commented on docs/userguide
> +[[_smart_borders]]
Could you mention smart_borders in the Syntax or Example with a comment stating that it’s an old syntax for “hide_edge_borders smart”? I’d like to make sure that people can Ctrl+f this page for every line of their config file and find details on it.

2024-01-29 07:44 UTC, stapelberg commented on src/config_directives.c
> +    ELOG("smart_borders is deprecated. Please use hide_edge_borders instead.\n");
Why raise an error? We could just remove this line and translate smart_borders into hide_edge_borders == smart indefinitely. I don’t think it’s necessary to bother users to update their config file for this.

2024-01-29 18:35 UTC, orestisfl commented on src/config_directives.c
> +    ELOG("smart_borders is deprecated. Please use hide_edge_borders instead.\n");
Moved the warning only when there is a conflict.

2024-01-29 18:38 UTC, orestisfl commented on docs/userguide
> +[[_smart_borders]]
I feel if we mention the old syntax as an example it's going to lead to people copying it. Added a simple mention of it.

2024-01-30 07:53 UTC, stapelberg approved these changes

2024-01-30 07:53 UTC, merged