GH action: Upload built htmls
i3/i3 pull request #6070
Opened 2024-05-20 19:30 UTC by orestisfl

2024-05-21 15:17 UTC, stapelberg commented
Can you explain a little more what this will change (where will the HTML files go?) and what the motivation is for this change? Thanks

2024-05-21 15:51 UTC, orestisfl commented
You can find the files from the job output:
Artifact i3-docs.zip successfully finalized. Artifact ID 1520396887
Artifact i3-docs has been successfully uploaded! Final size is 162805 bytes. Artifact ID is 1520396887
Artifact download URL: https://github.com/i3/i3/actions/runs/9163984370/artifacts/1520396887

As for motivation, I guess it's free, quick to implement, and allows us to verify that PRs are formatted correctly without needing to pull & build.

2024-06-09 08:35 UTC, stapelberg requested changes

2024-06-09 08:35 UTC, stapelberg commented on .github/workflows/main.yml
> +    - name: Upload docs html
Can you make this “Upload docs html for manual inspection” please? I want to stress that this isn’t related to publishing the docs.

2024-06-20 05:05 UTC, stapelberg approved these changes

2024-06-20 05:05 UTC, merged