provide I3_WINDOW_ID to processes called with exec when possible
i3/i3 pull request #6160
Opened 2024-07-16 04:52 UTC by doy

fixes #1729

2025-12-13 07:40 UTC, stapelberg requested changes
Sorry for the slow review. Do you want to improve this PR before the upcoming release? (If not, that’s also fine, but if so, I can try to wait for this before the release.)

2025-12-13 07:40 UTC, stapelberg commented on testcases/t/165-for_window.t
> +    sleep(1);
This might seem pedantic, but we will not accept `sleep` calls into the testsuite. Our testsuite has been optimized to run within a second or two (on modern computers), so sleeping for a second increases the total testsuite runtime excessively.

Instead, maybe we could use a FIFO here. search for `mkfifo` in the `testcases` directory for a few examples.

2025-12-13 07:40 UTC, stapelberg commented on testcases/t/165-for_window.t
> +for (0..3) {
Why do this multiple times instead of just once? Wouldn’t running just once give us the same guarantees?

2025-12-13 07:40 UTC, stapelberg commented on src/startup.c
> +        if (window_id != 0) {
Here and elsewhere in the PR: always use `XCB_NONE` for comparing `xcb_window_t` types instead of `0`

2025-12-20 02:54 UTC, doy commented
fixed!

2025-12-20 07:00 UTC, stapelberg approved these changes

2025-12-20 07:04 UTC, merged